<?php
/**
 * Add 2 more lessons to each module (all difficulties).
 * Run: php add_more_lessons.php
 */

$path = __DIR__ . '/data/modules.json';
$json = file_get_contents($path);
$modules = json_decode($json, true);
if (!is_array($modules)) {
    die("Failed to load modules.json\n");
}

// 2 additional lessons per module (id suffix l6, l7 for beginner; int-l6/l7, adv-l6/l7)
$moreByModule = [
    'html-basics' => [
        ['id' => 'html-l6', 'title' => 'Block vs inline elements', 'content' => 'Understand how elements flow on the page', 'details' => ['Block elements (div, p, h1) start on a new line and take full width.', 'Inline elements (span, a, strong) sit in the line and only take needed space.', 'display: block and display: inline change this behavior in CSS.', 'Hint: div is a block-level element by default.'], 'example_code' => "<div>Block</div><span>Inline</span>", 'key_points' => ['Block: new line, full width', 'Inline: in flow', 'display in CSS'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Which is a block-level element?', 'code_template' => '<___>Section</___>', 'options' => ['div', 'span', 'a', 'strong'], 'answer' => 'div']],
        ['id' => 'html-l7', 'title' => 'Comments & best practices', 'content' => 'Comment your HTML and write clean code', 'details' => ['HTML comments: <!-- comment --> are ignored by the browser.', 'Use comments to explain sections or temporarily hide markup.', 'Indent nested elements; use lowercase for tags and attributes.'], 'example_code' => "<!-- Main content -->\n<main>\n  <p>Hello</p>\n</main>", 'key_points' => ['<!-- --> for comments', 'Indent nested elements', 'Lowercase tags'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'How do you start an HTML comment?', 'code_template' => '___ comment -->', 'options' => ['<!--', '<!', '<?', '/*'], 'answer' => '<!--']],
    ],
    'html-basics-intermediate' => [
        ['id' => 'html-int-l6', 'title' => 'Embedding media', 'content' => 'Video and audio with HTML5', 'details' => ['<video src="x.mp4" controls></video> for video; <audio> for audio.', 'Multiple <source> inside for format fallback.', 'poster attribute on video shows a preview image.'], 'example_code' => '<video controls><source src="clip.mp4" type="video/mp4"></video>', 'key_points' => ['<video> and <audio>', '<source> for fallback', 'controls attribute'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What does the controls attribute do on video?', 'code' => '<video controls>', 'options' => ['Shows play/pause UI', 'Auto-plays', 'Mutes', 'Loops'], 'answer' => 'Shows play/pause UI']],
        ['id' => 'html-int-l7', 'title' => 'Form validation attributes', 'content' => 'Built-in validation with HTML5', 'details' => ['required makes a field mandatory before submit.', 'pattern="regex" for custom validation; min/max for numbers.', 'type="email", type="number", type="url" add browser validation.'], 'example_code' => '<input type="email" required placeholder="you@example.com">', 'key_points' => ['required', 'pattern, min, max', 'type for validation'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Attribute to make an input mandatory?', 'code_template' => '<input type="text" ___>', 'options' => ['required', 'must', 'validate', 'mandatory'], 'answer' => 'required']],
    ],
    'html-basics-advanced' => [
        ['id' => 'html-adv-l6', 'title' => 'Web Components intro', 'content' => 'Custom elements with JavaScript', 'details' => ['customElements.define("my-tag", class extends HTMLElement { }).', 'Custom elements must have a hyphen in the name.', 'Lifecycle: connectedCallback, disconnectedCallback, attributeChangedCallback.'], 'example_code' => "customElements.define('my-card', class extends HTMLElement {});", 'key_points' => ['customElements.define', 'Hyphen in name', 'Lifecycle callbacks'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'Custom element names must contain what?', 'code' => 'customElements.define("x-card", ...)', 'options' => ['A hyphen', 'Two words', 'Capital letter', 'Numbers'], 'answer' => 'A hyphen']],
        ['id' => 'html-adv-l7', 'title' => 'Preload & prefetch', 'content' => 'Hint critical resources', 'details' => ['<link rel="preload" href="font.woff2" as="font"> loads early.', 'prefetch for next-page resources; preconnect for origins.', 'Use for critical assets to improve LCP and FCP.'], 'example_code' => '<link rel="preload" href="main.js" as="script">', 'key_points' => ['preload for critical', 'prefetch for next page', 'as attribute'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'rel value to load a resource early?', 'code_template' => '<link rel="___" href="x.js" as="script">', 'options' => ['preload', 'load', 'early', 'fetch'], 'answer' => 'preload']],
    ],
    'javascript-fundamentals' => [
        ['id' => 'js-l6', 'title' => 'Objects & properties', 'content' => 'Store key-value pairs in objects', 'details' => ['const obj = { name: "Alice", age: 25 }; dot: obj.name, bracket: obj["age"].', 'Add: obj.city = "NY"; delete obj.age;', 'Object.keys(obj), Object.values(obj) for iteration.'], 'example_code' => "const user = { name: 'Bob', age: 30 };\nconsole.log(user.name);", 'key_points' => ['{} for objects', 'Dot and bracket access', 'Object.keys/values'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What is user.name?', 'code' => "const user = { name: 'Ali' }; console.log(user.name);", 'options' => ['Ali', 'user', 'undefined', 'name'], 'answer' => 'Ali']],
        ['id' => 'js-l7', 'title' => 'Template literals', 'content' => 'Strings with expressions', 'details' => ['Backticks for template literals: `Hello ${name}`.', 'Multi-line strings without \\n; ${expr} embeds expressions.', 'Tagged templates can process the string (e.g. sanitize).'], 'example_code' => 'const x = 5;' . "\n" . 'console.log(`Result: $' . '{x * 2}`);', 'key_points' => ['Backticks', '${} for expressions', 'Multi-line'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Which character wraps template literals?', 'code_template' => '___Hello ${name}___', 'options' => ['`', '"', "'", '~'], 'answer' => '`']],
    ],
    'javascript-fundamentals-intermediate' => [
        ['id' => 'js-int-l6', 'title' => 'Spread & rest', 'content' => '... operator', 'details' => ['Spread: [...arr], { ...obj } copy or merge.', 'Rest in params: function(a, b, ...rest) { } collects the rest.', 'Rest in destructuring: const [first, ...others] = arr;'], 'example_code' => "const a = [1,2]; const b = [...a, 3];", 'key_points' => ['Spread for copy/merge', 'Rest in params', 'Rest in destructuring'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What is b? const a=[1,2]; const b=[...a,3];', 'code' => 'const b = [...[1,2], 3];', 'options' => ['[1,2,3]', '[3,1,2]', '6', 'Error'], 'answer' => '[1,2,3]']],
        ['id' => 'js-int-l7', 'title' => 'Array methods: find, some, every', 'content' => 'More array utilities', 'details' => ['find(el => condition) returns first match; findIndex returns index.', 'some(el => condition) true if any match; every if all match.', 'includes(value) for simple membership check.'], 'example_code' => "const n = [1,2,3].find(x => x > 2);", 'key_points' => ['find, findIndex', 'some, every', 'includes'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What does [1,2,3].find(x => x > 2) return?', 'code' => '[1,2,3].find(x => x > 2)', 'options' => ['3', '2', 'true', 'undefined'], 'answer' => '3']],
    ],
    'javascript-fundamentals-advanced' => [
        ['id' => 'js-adv-l6', 'title' => 'Symbols & iterators', 'content' => 'Unique keys and iteration', 'details' => ['Symbol() creates a unique value; good for object keys.', 'Symbol.iterator defines how for...of loops over an object.', 'Generators: function* gen() { yield 1; } for lazy sequences.'], 'example_code' => "const sym = Symbol('id');\nconst o = { [sym]: 42 };", 'key_points' => ['Symbol() unique', 'Symbol.iterator', 'Generators'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Type that creates a unique value?', 'code_template' => 'const s = ___(\'key\');', 'options' => ['Symbol', 'Unique', 'Key', 'Id'], 'answer' => 'Symbol']],
        ['id' => 'js-adv-l7', 'title' => 'Map & Set', 'content' => 'Keyed and unique collections', 'details' => ['Map: any key type; .set(k,v), .get(k), .has(k), .size.', 'Set: unique values only; .add(v), .has(v), .delete(v).', 'Prefer Map over plain object when keys are non-strings.'], 'example_code' => "const m = new Map();\nm.set('a', 1); m.get('a');", 'key_points' => ['Map: key-value', 'Set: unique values', '.size not .length'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What does new Set([1,1,2]).size return?', 'code' => 'new Set([1,1,2]).size', 'options' => ['2', '3', '1', '0'], 'answer' => '2']],
    ],
    'php-development' => [
        ['id' => 'php-l6', 'title' => 'Include & require', 'content' => 'Reuse code across files', 'details' => ['include "file.php"; or require "file.php"; runs another file.', 'require stops on missing file; include continues with a warning.', 'include_once and require_once prevent double inclusion.'], 'example_code' => "<?php\nrequire 'config.php';\ninclude 'header.php';\n?>", 'key_points' => ['include, require', 'require for critical', '_once to avoid duplicate'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Which stops execution if file is missing?', 'code_template' => '___ "file.php";', 'options' => ['require', 'include', 'load', 'use'], 'answer' => 'require']],
        ['id' => 'php-l7', 'title' => 'Working with strings', 'content' => 'Common string functions', 'details' => ['strlen($s), str_replace($find, $replace, $s), substr($s, start, len).', 'strtolower, strtoupper, trim; explode(delim, $s) splits to array.', 'implode(glue, $arr) joins array to string.'], 'example_code' => "<?php\necho str_replace('old', 'new', 'Hello old');\n?>", 'key_points' => ['str_replace, substr', 'explode, implode', 'trim, strlen'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What does str_replace("a","o","cat") return?', 'code' => 'str_replace("a","o","cat")', 'options' => ['cot', 'cat', 'coot', 'ct'], 'answer' => 'cot']],
    ],
    'php-development-intermediate' => [
        ['id' => 'php-int-l6', 'title' => 'Error reporting & logging', 'content' => 'Handle and log errors', 'details' => ['error_reporting(E_ALL); ini_set("display_errors", 1); in dev.', 'error_log($msg) writes to server log.', 'set_error_handler() for custom handler.'], 'example_code' => "<?php\nerror_log('Something failed');\n?>", 'key_points' => ['error_reporting', 'error_log', 'set_error_handler'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Function to write to server error log?', 'code_template' => '___("message");', 'options' => ['error_log', 'log', 'write_log', 'error'], 'answer' => 'error_log']],
        ['id' => 'php-int-l7', 'title' => 'JSON encode & decode', 'content' => 'Work with JSON in PHP', 'details' => ['json_encode($data) produces JSON string; json_decode($str, true) gives array.', 'Options: JSON_PRETTY_PRINT, JSON_UNESCAPED_UNICODE.', 'json_decode returns null on invalid JSON; check json_last_error().'], 'example_code' => '<?php' . "\n" . '$arr = json_decode($jsonString, true);' . "\n" . 'echo json_encode($arr);' . "\n" . '?>', 'key_points' => ['json_encode, json_decode', 'Second param true for array', 'json_last_error'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What does json_decode(\'{"a":1}\', true) return?', 'code' => 'json_decode(\'{"a":1}\', true)', 'options' => ['["a"=>1]', 'Array', 'Object', '1'], 'answer' => 'Array']],
    ],
    'php-development-advanced' => [
        ['id' => 'php-adv-l6', 'title' => 'Type declarations', 'content' => 'Strict types and type hints', 'details' => ['declare(strict_types=1); at top enforces strict types.', 'Function params and return: function f(int $x): string { }.', 'Nullable: ?string means string|null.'], 'example_code' => "<?php\ndeclare(strict_types=1);\nfunction add(int \$a, int \$b): int { return \$a + \$b; }\n?>", 'key_points' => ['declare(strict_types=1)', 'Param and return types', '? for nullable'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Declaration to enforce strict types?', 'code_template' => '___ (strict_types=1);', 'options' => ['declare', 'strict', 'types', 'enable'], 'answer' => 'declare']],
        ['id' => 'php-adv-l7', 'title' => 'Attributes (PHP 8)', 'content' => 'Metadata with attributes', 'details' => ['#[Route(\'/path\')] above classes/methods for metadata.', 'Reflection API reads attributes at runtime.', 'Use for routing, validation, serialization.'], 'example_code' => "<?php\n#[Route('/api/users')]\nclass UserController { }\n?>", 'key_points' => ['#[] syntax', 'Reflection reads them', 'Routing, validation'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What do PHP 8 attributes provide?', 'code' => '#[Route("/home")]', 'options' => ['Metadata', 'Routing only', 'Security', 'Speed'], 'answer' => 'Metadata']],
    ],
    'sql-databases' => [
        ['id' => 'sql-l6', 'title' => 'CREATE TABLE', 'content' => 'Define tables and columns', 'details' => ['CREATE TABLE name (col type constraints, ...);', 'Common types: INT, VARCHAR(n), TEXT, DATE, DECIMAL(p,s).', 'PRIMARY KEY, FOREIGN KEY, NOT NULL, UNIQUE, DEFAULT.'], 'example_code' => "CREATE TABLE users (\n  id INT PRIMARY KEY AUTO_INCREMENT,\n  name VARCHAR(100) NOT NULL\n);", 'key_points' => ['CREATE TABLE', 'Column types', 'PRIMARY KEY, NOT NULL'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Keyword to define a new table?', 'code_template' => '___ TABLE users (id INT);', 'options' => ['CREATE', 'DEFINE', 'NEW', 'ADD'], 'answer' => 'CREATE']],
        ['id' => 'sql-l7', 'title' => 'DISTINCT & sorting', 'content' => 'Unique rows and ORDER BY', 'details' => ['SELECT DISTINCT col FROM t; removes duplicate rows in result.', 'ORDER BY col ASC/DESC; multiple: ORDER BY a, b DESC.', 'NULLs sort first or last depending on DB.'], 'example_code' => "SELECT DISTINCT country FROM users;\nSELECT * FROM products ORDER BY price DESC;", 'key_points' => ['DISTINCT', 'ORDER BY ASC/DESC', 'Multiple columns'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What does DISTINCT do?', 'code' => 'SELECT DISTINCT status FROM orders', 'options' => ['Removes duplicate rows', 'Sorts', 'Limits', 'Counts'], 'answer' => 'Removes duplicate rows']],
    ],
    'sql-databases-intermediate' => [
        ['id' => 'sql-int-l6', 'title' => 'CASE expressions', 'content' => 'Conditional logic in SQL', 'details' => ['CASE WHEN cond THEN val WHEN ... ELSE val END.', 'Use in SELECT, WHERE, ORDER BY.', 'Simple form: CASE col WHEN \'a\' THEN 1 END.'], 'example_code' => "SELECT name, CASE WHEN score >= 60 THEN 'Pass' ELSE 'Fail' END FROM students;", 'key_points' => ['CASE WHEN THEN ELSE END', 'In SELECT/WHERE/ORDER', 'Conditional output'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'SQL keyword for conditional expression?', 'code_template' => 'SELECT ___ WHEN x>0 THEN 1 END;', 'options' => ['CASE', 'IF', 'WHEN', 'COND'], 'answer' => 'CASE']],
        ['id' => 'sql-int-l7', 'title' => 'Date & time functions', 'content' => 'Work with dates in SQL', 'details' => ['NOW(), CURDATE(), CURTIME() for current date/time.', 'DATE_FORMAT(col, \'%Y-%m-%d\'), DATE_ADD, DATEDIFF.', 'Filter: WHERE date_col >= \'2024-01-01\'.'], 'example_code' => "SELECT NOW(), DATE_FORMAT(created_at, '%Y-%m-%d');", 'key_points' => ['NOW, CURDATE', 'DATE_FORMAT', 'DATE_ADD, DATEDIFF'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What does NOW() return?', 'code' => 'SELECT NOW();', 'options' => ['Current date and time', 'Current date only', 'Timestamp', 'Number'], 'answer' => 'Current date and time']],
    ],
    'sql-databases-advanced' => [
        ['id' => 'sql-adv-l6', 'title' => 'Views', 'content' => 'Virtual tables', 'details' => ['CREATE VIEW name AS SELECT ...; view is a stored query.', 'Query a view like a table; some views are updatable.', 'Simplifies complex queries and enforces security.'], 'example_code' => "CREATE VIEW active_users AS SELECT * FROM users WHERE active = 1;", 'key_points' => ['CREATE VIEW AS SELECT', 'Query like table', 'Updatable views'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Object that stores a SELECT as a virtual table?', 'code_template' => 'CREATE ___ AS SELECT ...;', 'options' => ['VIEW', 'TABLE', 'QUERY', 'SELECT'], 'answer' => 'VIEW']],
        ['id' => 'sql-adv-l7', 'title' => 'Backup & restore', 'content' => 'Export and import data', 'details' => ['mysqldump for logical backup; binary logs for point-in-time.', 'Restore: mysql < backup.sql or SOURCE backup.sql.', 'Regular backups and test restores are critical.'], 'example_code' => "-- Export: mysqldump -u user -p dbname > backup.sql\n-- Restore: mysql -u user -p dbname < backup.sql", 'key_points' => ['mysqldump', 'mysql < file', 'Test restores'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'Common tool for MySQL logical backup?', 'code' => 'mysqldump', 'options' => ['Backup tool', 'Query tool', 'Monitor', 'Editor'], 'answer' => 'Backup tool']],
    ],
    'css-styling' => [
        ['id' => 'css-l6', 'title' => 'Text styling', 'content' => 'Fonts and text properties', 'details' => ['font-family, font-size, font-weight (bold), font-style (italic).', 'text-align, line-height, letter-spacing, text-decoration.', 'Google Fonts: @import or <link> for web fonts.'], 'example_code' => "font-family: 'Open Sans', sans-serif;\nfont-size: 16px;\ntext-align: center;", 'key_points' => ['font-family, size, weight', 'text-align, line-height', 'Web fonts'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Property to set bold text?', 'code_template' => 'font-___: bold;', 'options' => ['weight', 'style', 'bold', 'width'], 'answer' => 'weight']],
        ['id' => 'css-l7', 'title' => 'Borders & shadows', 'content' => 'Outline borders and box-shadow', 'details' => ['border: 1px solid #ccc; or border-width, border-color, border-radius.', 'box-shadow: offset-x offset-y blur color; multiple shadows allowed.', 'outline is drawn outside border (e.g. focus).'], 'example_code' => "border: 1px solid #ddd;\nborder-radius: 8px;\nbox-shadow: 0 2px 4px rgba(0,0,0,0.1);", 'key_points' => ['border, border-radius', 'box-shadow', 'outline'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What does box-shadow create?', 'code' => 'box-shadow: 0 2px 4px gray', 'options' => ['Drop shadow', 'Border', 'Background', 'Blur'], 'answer' => 'Drop shadow']],
    ],
    'css-styling-intermediate' => [
        ['id' => 'css-int-l6', 'title' => 'Flexbox deep dive', 'content' => 'flex-grow, shrink, basis', 'details' => ['flex: 1 1 0 means grow 1, shrink 1, basis 0.', 'flex-wrap: wrap; align-content for multi-line.', 'flex-direction: column-reverse for order.'], 'example_code' => ".item { flex: 1 1 200px; }\n.container { flex-wrap: wrap; }", 'key_points' => ['flex shorthand', 'flex-wrap, align-content', 'flex-direction'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Property to let flex items wrap to next line?', 'code_template' => 'flex-___: wrap;', 'options' => ['wrap', 'flow', 'break', 'next'], 'answer' => 'wrap']],
        ['id' => 'css-int-l7', 'title' => 'Position: sticky', 'content' => 'Sticky positioning', 'details' => ['position: sticky; top: 0; sticks within parent while scrolling.', 'Behaves like relative until threshold, then fixed within container.', 'Use for sticky headers or sidebars.'], 'example_code' => ".header { position: sticky; top: 0; background: white; }", 'key_points' => ['sticky', 'top/left threshold', 'Within parent'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What does position: sticky do?', 'code' => 'position: sticky; top: 0;', 'options' => ['Sticks when scrolling', 'Fixes to viewport', 'Hides', 'Centers'], 'answer' => 'Sticks when scrolling']],
    ],
    'css-styling-advanced' => [
        ['id' => 'css-adv-l6', 'title' => 'Logical properties', 'content' => 'margin-inline, padding-block', 'details' => ['margin-inline-start/end, padding-block for RTL-friendly layout.', 'inset: 0 instead of top/right/bottom/left.', 'Adapts to writing direction and flow.'], 'example_code' => "margin-inline: 1rem;\npadding-block: 0.5rem;", 'key_points' => ['margin-inline, padding-block', 'inset', 'RTL support'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Logical property for horizontal margin?', 'code_template' => 'margin-___: 1rem;', 'options' => ['inline', 'horizontal', 'x', 'h'], 'answer' => 'inline']],
        ['id' => 'css-adv-l7', 'title' => 'Scroll-driven animations', 'content' => 'Animate on scroll', 'details' => ['animation-timeline: scroll() ties animation to scroll position.', 'view() and scroll() for scroll-linked effects.', 'Newer feature; check browser support.'], 'example_code' => "animation: fade linear;\nanimation-timeline: scroll();", 'key_points' => ['animation-timeline', 'scroll(), view()', 'Scroll-linked'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What does animation-timeline: scroll() do?', 'code' => 'animation-timeline: scroll();', 'options' => ['Ties animation to scroll', 'Scrolls page', 'Pauses animation', 'Nothing'], 'answer' => 'Ties animation to scroll']],
    ],
];

foreach ($modules as &$module) {
    $id = $module['id'];
    if (!isset($moreByModule[$id])) {
        continue;
    }
    $module['lessons'] = array_merge($module['lessons'], $moreByModule[$id]);
    $totalXp = 0;
    foreach ($module['lessons'] as $lesson) {
        $totalXp += (int) ($lesson['xp'] ?? 50);
    }
    $module['total_xp'] = $totalXp;
}

$out = json_encode($modules, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
if ($out === false) {
    die("JSON encode failed\n");
}
file_put_contents($path, $out);
echo "Added 2 more lessons to each of the 15 modules. Total lessons per module now 7.\n";
