<?php
/**
 * Add 10 more lessons to each of the 15 modules.
 * Run: php add_10_lessons_per_module.php
 */

$path = __DIR__ . '/data/modules.json';
$json = file_get_contents($path);
$modules = json_decode($json, true);
if (!is_array($modules)) {
    die("Failed to load modules.json\n");
}

function makeLesson($id, $title, $content, $details, $exampleCode, $keyPoints, $gameType, $question, $codeTemplateOrCode, $options, $answer) {
    $game = [
        'type' => $gameType,
        'question' => $question,
        'options' => $options,
        'answer' => $answer
    ];
    if ($gameType === 'fill_blank') {
        $game['code_template'] = $codeTemplateOrCode;
    } else {
        $game['code'] = $codeTemplateOrCode;
    }
    return [
        'id' => $id,
        'title' => $title,
        'content' => $content,
        'details' => $details,
        'example_code' => $exampleCode,
        'key_points' => $keyPoints,
        'xp' => 50,
        'game' => $game
    ];
}

$additions = [];

// HTML Basics (beginner) - l8 to l17
$additions['html-basics'] = [
    makeLesson('html-l8', 'Quotations & code', 'Quote text and show code', ['<q> for short quotes, <blockquote> for blocks.', '<code> for inline code, <pre> for blocks.', 'Use <pre><code> together for snippets.'], '<code>let x = 1;</code>', ['<q>, <blockquote>', '<code>, <pre>', 'Semantic meaning'], 'fill_blank', 'Tag for inline code?', '<___>x + 1</___>', ['code', 'pre', 'var', 'script'], 'code'),
    makeLesson('html-l9', 'Div & span', 'Group and style content', ['<div> is a block container; <span> is inline.', 'Use for styling hooks or grouping.', 'IDs should be unique; classes can repeat.'], '<div class="card"><span class="label">Hi</span></div>', ['div block, span inline', 'class vs id', 'Containers'], 'predict_output', 'What is span by default?', '<span>text</span>', ['Inline', 'Block', 'Hidden', 'Bold'], 'Inline'),
    makeLesson('html-l10', 'Strong & emphasis', 'Semantic text emphasis', ['<strong> for importance, <b> for bold only.', '<em> for stress, <i> for italic only.', 'Prefer strong/em for accessibility.'], '<strong>Warning</strong> <em>required</em>', ['strong, em semantic', 'b, i presentational', 'Accessibility'], 'fill_blank', 'Tag for important text?', '<___>Required</___>', ['strong', 'b', 'bold', 'important'], 'strong'),
    makeLesson('html-l11', 'Line break & horizontal rule', 'Break lines and sections', ['<br> is self-closing; forces a line break.', '<hr> draws a horizontal line between sections.', 'Use sparingly; prefer block elements.'], '<p>Line one<br>Line two</p><hr>', ['br for line break', 'hr for divider', 'Self-closing'], 'fill_blank', 'Tag for a line break?', 'Hello<___>World', ['br', 'break', 'lb', 'nl'], 'br'),
    makeLesson('html-l12', 'Abbreviations & citations', 'Abbr and cite tags', ['<abbr title="full">short</abbr> for abbreviations.', '<cite> for work titles (book, film).', 'title on abbr shows full form on hover.'], '<abbr title="World Wide Web">WWW</abbr>', ['abbr with title', 'cite for titles', 'Hover tooltip'], 'predict_output', 'What does abbr title do?', '<abbr title="HyperText">HTML</abbr>', ['Shows on hover', 'Required', 'Link', 'Nothing'], 'Shows on hover'),
    makeLesson('html-l13', 'Button vs submit', 'Buttons in forms', ['<button type="submit"> submits the form.', '<button type="button"> does not submit.', 'type="reset" clears the form.'], '<button type="submit">Send</button>', ['submit, button, reset', 'type matters', 'Inside form'], 'fill_blank', 'Button type that does NOT submit?', '<button type="___">Click</button>', ['button', 'submit', 'none', 'normal'], 'button'),
    makeLesson('html-l14', 'Fieldset & legend', 'Group form fields', ['<fieldset> groups related inputs.', '<legend> is the fieldset caption.', 'Improves accessibility and structure.'], '<fieldset><legend>Address</legend>...</fieldset>', ['fieldset groups', 'legend caption', 'Accessibility'], 'fill_blank', 'Tag for group of form fields?', '<___><legend>Name</legend></___>', ['fieldset', 'group', 'section', 'form'], 'fieldset'),
    makeLesson('html-l15', 'Placeholder & value', 'Input default content', ['placeholder shows hint when empty.', 'value sets default or submitted data.', 'placeholder is not a label replacement.'], '<input placeholder="Enter name" value="">', ['placeholder hint', 'value default', 'Not replacement for label'], 'predict_output', 'When is placeholder visible?', '<input placeholder="hint">', ['When field empty', 'Always', 'On focus only', 'Never'], 'When field empty'),
    makeLesson('html-l16', 'Multiple & file input', 'Multiple select and file upload', ['multiple on select allows many options.', '<input type="file"> for uploads.', 'accept limits file types (e.g. image/*).'], '<input type="file" accept="image/*">', ['multiple on select', 'type=file', 'accept attribute'], 'fill_blank', 'Input type for file upload?', '<input type="___" name="doc">', ['file', 'upload', 'document', 'attach'], 'file'),
    makeLesson('html-l17', 'Disabled & readonly', 'Non-editable inputs', ['disabled excludes from submit; greyed out.', 'readonly blocks edit but value is submitted.', 'Use for display or conditional fields.'], '<input readonly value="Fixed">', ['disabled not submitted', 'readonly submitted', 'Both block edit'], 'predict_output', 'Is disabled field value submitted?', '<input disabled value="x">', ['No', 'Yes', 'Sometimes', 'Depends'], 'No'),
];

// HTML Intermediate - int-l8 to int-l17
$additions['html-basics-intermediate'] = [
    makeLesson('html-int-l8', 'Picture element', 'Art direction with picture', ['<picture> with <source> for different images.', 'media attribute for viewport-based choice.', 'Fallback <img> inside picture.'], '<picture><source media="(min-width:800px)" srcset="large.jpg"><img src="small.jpg"></picture>', ['picture + source', 'media for breakpoints', 'img fallback'], 'fill_blank', 'Element for responsive image choice?', '<___><source><img></___>', ['picture', 'responsive', 'source', 'adaptive'], 'picture'),
    makeLesson('html-int-l9', 'Dialog element', 'Native modal dialog', ['<dialog> for modal or non-modal dialogs.', 'showModal() and show() to open.', 'method="dialog" on form closes dialog.'], '<dialog id="d"><form method="dialog"><button>Close</button></form></dialog>', ['dialog element', 'showModal()', 'method=dialog'], 'predict_output', 'What does dialog showModal() do?', 'dialog.showModal()', ['Opens as modal', 'Shows content', 'Submits', 'Closes'], 'Opens as modal'),
    makeLesson('html-int-l10', 'Meter & progress', 'Progress and meter', ['<progress value="70" max="100"> for task progress.', '<meter> for scalar value (e.g. disk usage).', 'Both have value; progress has max.'], '<progress value="50" max="100"></progress>', ['progress for tasks', 'meter for gauges', 'value and max'], 'fill_blank', 'Tag for completion progress?', '<___ value="50" max="100">', ['progress', 'meter', 'bar', 'percent'], 'progress'),
    makeLesson('html-int-l11', 'Output element', 'Calculated output', ['<output> displays result of a calculation.', 'Often used with form and oninput.', 'for attribute links to input ids.'], '<output for="a b">0</output>', ['output for results', 'for attribute', 'Calculation display'], 'predict_output', 'What is output element for?', '<output>', ['Displaying calculated result', 'Input', 'Button', 'Hidden'], 'Displaying calculated result'),
    makeLesson('html-int-l12', 'Optgroup', 'Group dropdown options', ['<optgroup label="Group"> groups <option>s.', 'Improves long select usability.', 'Label is not selectable.'], '<select><optgroup label="Fruits"><option>Apple</option></optgroup></select>', ['optgroup label', 'Groups options', 'Not selectable'], 'fill_blank', 'Tag to group select options?', '<select><___ label="A"><option></option></___></select>', ['optgroup', 'group', 'optiongroup', 'fieldset'], 'optgroup'),
    makeLesson('html-int-l13', 'Contenteditable', 'Editable content', ['contenteditable="true" makes element editable.', 'Browser handles typing; use for rich text.', 'Save with JS (e.g. innerHTML).'], '<div contenteditable="true">Edit me</div>', ['contenteditable', 'Browser editing', 'Save via JS'], 'predict_output', 'What does contenteditable do?', '<p contenteditable="true">', ['Allows in-place edit', 'Hides', 'Validates', 'Submits'], 'Allows in-place edit'),
    makeLesson('html-int-l14', 'Spellcheck attribute', 'Control spell checking', ['spellcheck="true" or "false" on inputs/textareas.', 'Default is browser-dependent.', 'lang attribute affects dictionary.'], '<textarea spellcheck="true"></textarea>', ['spellcheck attribute', 'true/false', 'lang matters'], 'fill_blank', 'Attribute to enable spell check?', '<textarea ___="true">', ['spellcheck', 'spell', 'check', 'dictionary'], 'spellcheck'),
    makeLesson('html-int-l15', 'Tabindex', 'Control focus order', ['tabindex="0" includes in tab order.', 'tabindex="-1" focusable by script only.', 'Positive values (avoid) set order.'], '<button tabindex="0">Click</button>', ['tabindex 0 and -1', 'Focus order', 'Avoid positive'], 'predict_output', 'What does tabindex="-1" mean?', 'tabindex="-1"', ['Focus by script only', 'Skip', 'First', 'Last'], 'Focus by script only'),
    makeLesson('html-int-l16', 'Download attribute', 'Trigger download', ['<a download> forces download instead of navigate.', 'download="filename" suggests save name.', 'Same-origin or blob URLs.'], '<a href="doc.pdf" download>Save PDF</a>', ['download on link', 'Suggested filename', 'Same-origin'], 'fill_blank', 'Attribute to force link download?', '<a href="x.pdf" ___>Save</a>', ['download', 'save', 'get', 'target'], 'download'),
    makeLesson('html-int-l17', 'Referrerpolicy', 'Control referrer', ['referrerpolicy on a, img, iframe.', 'no-referrer, same-origin, etc.', 'Privacy and security control.'], '<a href="https://other.com" referrerpolicy="no-referrer">', ['referrerpolicy', 'no-referrer', 'Privacy'], 'predict_output', 'What does no-referrer do?', 'referrerpolicy="no-referrer"', ['Sends no referrer', 'Blocks link', 'Encrypts', 'Validates'], 'Sends no referrer'),
];

// HTML Advanced - adv-l8 to adv-l17
$additions['html-basics-advanced'] = [
    makeLesson('html-adv-l8', 'Resource hints', 'dns-prefetch, preconnect', ['<link rel="dns-prefetch" href="https://api.com"> resolves DNS early.', 'preconnect also opens connection.', 'Reduces latency for third-party.'], '<link rel="preconnect" href="https://cdn.example.com">', ['dns-prefetch', 'preconnect', 'Third-party speed'], 'fill_blank', 'rel for opening connection early?', '<link rel="___" href="https://api.com">', ['preconnect', 'connect', 'dns', 'prefetch'], 'preconnect'),
    makeLesson('html-adv-l9', 'Decoding async', 'Image decoding', ['decoding="async" on img allows async decode.', 'decoding="sync" (default) blocks.', 'Improves scroll performance.'], '<img src="big.jpg" decoding="async">', ['decoding async/sync', 'Off main thread', 'Performance'], 'predict_output', 'What does decoding="async" do?', 'decoding="async"', ['Decode off main thread', 'Load async', 'Lazy load', 'Nothing'], 'Decode off main thread'),
    makeLesson('html-adv-l10', 'Fetchpriority', 'Hint load priority', ['fetchpriority="high" on LCP image.', 'fetchpriority="low" for below-fold.', 'Hint only; browser may ignore.'], '<img src="hero.jpg" fetchpriority="high">', ['fetchpriority', 'high/low', 'LCP hint'], 'fill_blank', 'Attribute to hint image priority?', '<img src="hero.jpg" ___="high">', ['fetchpriority', 'priority', 'fetch', 'importance'], 'fetchpriority'),
    makeLesson('html-adv-l11', 'Sandboxed iframes', 'Restrict iframe', ['sandbox on iframe restricts capabilities.', 'allow="scripts" to allow scripts.', 'Empty sandbox = maximum restriction.'], '<iframe sandbox="allow-scripts" src="..."></iframe>', ['sandbox attribute', 'allow scripts/forms', 'Security'], 'predict_output', 'Empty sandbox on iframe?', 'sandbox=""', ['Maximum restriction', 'No effect', 'Allows all', 'Blocks load'], 'Maximum restriction'),
    makeLesson('html-adv-l12', 'Import maps', 'Control module resolution', ['<script type="importmap"> maps bare specifiers.', 'Resolve import "lodash" to URL.', 'One import map per document.'], '<script type="importmap">{"imports":{"m":"/m.js"}}</script>', ['importmap', 'Bare specifiers', 'Module resolution'], 'fill_blank', 'Script type for import maps?', '<script type="___">', ['importmap', 'import', 'module-map', 'map'], 'importmap'),
    makeLesson('html-adv-l13', 'Link headers', 'HTTP link header', ['Link: </style.css>; rel=preload; as=style in HTTP.', 'Same effect as link rel=preload in HTML.', 'Use from server when you cannot change HTML.'], 'Link: </app.css>; rel=preload; as=style', ['Link HTTP header', 'preload from server', 'Same as HTML link'], 'predict_output', 'Where is Link preload sent?', 'Link: </x.css>; rel=preload', ['HTTP response header', 'HTML head', 'Both', 'Nowhere'], 'HTTP response header'),
    makeLesson('html-adv-l14', 'Integrity attribute', 'SRI for scripts/styles', ['integrity="sha384-..." on script/link.', 'Browser verifies hash of resource.', 'Subresource Integrity (SRI).'], '<script src="lib.js" integrity="sha384-...">', ['integrity', 'SRI', 'Hash verification'], 'fill_blank', 'Attribute for script integrity check?', '<script src="x.js" ___="sha384-...">', ['integrity', 'hash', 'checksum', 'verify'], 'integrity'),
    makeLesson('html-adv-l15', 'Nonce for CSP', 'Script nonce', ['nonce="random" on script; same in CSP header.', 'Content-Security-Policy: script-src \'nonce-xxx\'.', 'Allows only inline scripts with matching nonce.'], '<script nonce="abc123">...</script>', ['nonce on script', 'CSP nonce-xxx', 'Allow inline'], 'predict_output', 'What is nonce used with?', 'nonce="random"', ['CSP script-src', 'CORS', 'Cookie', 'Cache'], 'CSP script-src'),
    makeLesson('html-adv-l16', 'Blocking vs defer', 'Script loading', ['defer: run after parse, order kept.', 'Blocking: no attribute, stops parse.', 'async: run when ready, order not kept.'], '<script src="app.js" defer></script>', ['defer after parse', 'Blocking stops parse', 'async order not kept'], 'fill_blank', 'Attribute to run script after parse?', '<script src="x.js" ___>', ['defer', 'async', 'after', 'load'], 'defer'),
    makeLesson('html-adv-l17', 'Manifest & PWA', 'Web app manifest', ['manifest link to JSON with name, icons, start_url.', 'Enables Add to Home Screen, standalone.', 'Part of PWA (Progressive Web App).'], '<link rel="manifest" href="/manifest.json">', ['manifest', 'PWA', 'Add to Home Screen'], 'predict_output', 'What does a manifest enable?', 'rel="manifest"', ['Add to Home Screen', 'Faster load', 'Offline only', 'Nothing'], 'Add to Home Screen'),
];

// JavaScript beginner - js-l8 to js-l17
$additions['javascript-fundamentals'] = [
    makeLesson('js-l8', 'Functions basics', 'Define and call functions', ['function name() { } or const name = function() { }.', 'Call with name().', 'return sends a value back.'], "function greet() { return 'Hi'; }\nconsole.log(greet());", ['function keyword', 'Call with ()', 'return'], 'predict_output', 'What does greet() return?', "function greet(){ return 'ok'; } greet();", ['ok', 'undefined', 'greet', 'function'], 'ok'),
    makeLesson('js-l9', 'Parameters', 'Pass data into functions', ['function add(a, b) { return a + b; }', 'Arguments passed by position.', 'Extra args ignored; missing are undefined.'], 'function double(n) { return n * 2; } double(5);', ['Parameters in ()', 'Arguments when calling', 'Order matters'], 'fill_blank', 'Where do function parameters go?', 'function add(___, b) { }', ['a', 'x', 'first', '1'], 'a'),
    makeLesson('js-l10', 'Return values', 'Getting data back', ['return value; exits and returns.', 'return; returns undefined.', 'Only one return value (use object/array for more).'], 'function id(x) { return x; } id(10);', ['return value', 'return; is undefined', 'Single value'], 'predict_output', 'What is returned?', 'function f(){ return 2; return 3; } f();', ['2', '3', 'undefined', 'Error'], '2'),
    makeLesson('js-l11', 'String methods', 'Work with strings', ['.length, .toUpperCase(), .toLowerCase().', '.trim() removes whitespace at ends.', '.includes(s), .startsWith(s), .endsWith(s).'], "'hello'.toUpperCase()", ['length, toUpperCase', 'trim', 'includes, startsWith'], 'predict_output', "What is '  hi  '.trim()?", "'  hi  '.trim()", ['hi', '  hi  ', 'hi  ', '  hi'], 'hi'),
    makeLesson('js-l12', 'Number methods', 'Math and numbers', ['Number.isInteger(x), Number.parseFloat(s).', 'Math.floor, Math.ceil, Math.round.', 'toFixed(n) for decimal places (returns string).'], 'Math.floor(3.7)', ['Math.floor/ceil/round', 'Number.parseFloat', 'toFixed'], 'predict_output', 'What is Math.ceil(2.1)?', 'Math.ceil(2.1)', ['3', '2', '2.1', '0'], '3'),
    makeLesson('js-l13', 'Boolean & comparison', 'true, false, comparisons', ['=== strict equality; !== strict inequality.', '>, <, >=, <= for numbers.', 'Avoid == (loose equality).'], '5 === 5', ['=== and !==', '>, <, >=, <=', 'Avoid =='], 'predict_output', 'What is 10 !== 10?', '10 !== 10', ['false', 'true', '0', 'undefined'], 'false'),
    makeLesson('js-l14', 'Logical AND OR', '&& and ||', ['a && b: true only if both true.', 'a || b: true if either true.', 'Short-circuit: && stops at first false.'], 'true && false', ['&& both true', '|| either true', 'Short-circuit'], 'predict_output', 'What is true && false?', 'true && false', ['false', 'true', 'undefined', '0'], 'false'),
    makeLesson('js-l15', 'Null & undefined', 'Missing values', ['undefined: variable not assigned.', 'null: intentional absence of value.', 'Check with x == null or x === undefined.'], 'let x; console.log(x);', ['undefined unassigned', 'null intentional', 'Checking'], 'predict_output', 'What is let a; console.log(a);?', 'let a; console.log(a);', ['undefined', 'null', '0', 'Error'], 'undefined'),
    makeLesson('js-l16', 'typeof operator', 'Check types', ['typeof x returns "string", "number", "boolean", "undefined", "object", "function".', 'typeof null is "object" (quirk).', 'Use for basic type checks.'], 'typeof 42', ['typeof returns string', 'typeof null is object', 'Type check'], 'predict_output', 'What is typeof "hello"?', 'typeof "hello"', ['string', 'String', 'text', 'undefined'], 'string'),
    makeLesson('js-l17', 'Console methods', 'Logging and debugging', ['console.log, console.error, console.warn.', 'console.table for arrays/objects.', 'console.time/timeEnd for timing.'], 'console.log("hello"); console.table([1,2]);', ['log, error, warn', 'table', 'time/timeEnd'], 'fill_blank', 'Console method for tabular data?', 'console.___(arr);', ['table', 'grid', 'list', 'show'], 'table'),
];

// JS Intermediate - js-int-l8 to js-int-l17
$additions['javascript-fundamentals-intermediate'] = [
    makeLesson('js-int-l8', 'Optional chaining', 'Safe property access', ['obj?.prop returns undefined if obj is null/undefined.', 'obj?.method?.() for method calls.', 'Avoids "cannot read property of undefined".'], 'user?.address?.city', ['?. for safe access', 'Avoids errors', 'Short-circuit'], 'predict_output', 'What is null?.x?', 'null?.x', ['undefined', 'null', 'Error', 'x'], 'undefined'),
    makeLesson('js-int-l9', 'Nullish coalescing', '?? operator', ['a ?? b returns b only when a is null or undefined.', 'Unlike ||, 0 and "" are kept.', 'Default values without losing falsy data.'], 'const n = value ?? 10;', ['?? for null/undefined', 'Keeps 0 and ""', 'Defaults'], 'predict_output', 'What is 0 ?? 5?', '0 ?? 5', ['0', '5', 'undefined', 'null'], '0'),
    makeLesson('js-int-l10', 'Array reduce', 'Reduce to single value', ['arr.reduce((acc, cur) => acc + cur, 0).', 'Accumulator and current; initial value optional.', 'Use for sum, max, flatten, etc.'], '[1,2,3].reduce((a,c) => a+c, 0)', ['reduce(acc, cur)', 'Initial value', 'Single result'], 'predict_output', 'What is [1,2,3].reduce((a,c)=>a+c,0)?', '[1,2,3].reduce((a,c)=>a+c,0)', ['6', '3', '123', 'undefined'], '6'),
    makeLesson('js-int-l11', 'Object.assign & spread', 'Copy and merge objects', ['Object.assign(target, ...sources) copies properties.', '{ ...a, ...b } merges; later wins.', 'Shallow copy only.'], 'const c = { ...a, ...b };', ['Object.assign', 'Spread merge', 'Shallow'], 'predict_output', 'What does { a:1, ...{ a:2 } } give?', '{ a:1, ...{ a:2 } }', ['{a:2}', '{a:1}', '{a:1,a:2}', 'Error'], '{a:2}'),
    makeLesson('js-int-l12', 'JSON stringify & parse', 'Serialize to JSON', ['JSON.stringify(obj) to string.', 'JSON.parse(str) to object.', 'Functions and undefined omitted in stringify.'], 'JSON.stringify({a:1})', ['stringify to JSON', 'parse from JSON', 'No functions'], 'predict_output', 'What is JSON.parse(\'{"x":1}\').x?', 'JSON.parse(\'{"x":1}\').x', ['1', 'undefined', '"1"', 'Error'], '1'),
    makeLesson('js-int-l13', 'SetTimeout & setInterval', 'Delayed execution', ['setTimeout(fn, ms) runs once after ms.', 'setInterval(fn, ms) repeats every ms.', 'Both return an id for clearTimeout/clearInterval.'], 'setTimeout(() => console.log("hi"), 1000);', ['setTimeout once', 'setInterval repeat', 'clear id'], 'fill_blank', 'Function to run once after delay?', '___(() => {}, 1000);', ['setTimeout', 'delay', 'wait', 'after'], 'setTimeout'),
    makeLesson('js-int-l14', 'Event object', 'Understanding events', ['Handler receives event object: element.addEventListener("click", e => {}).', 'e.target is element that received event.', 'e.preventDefault() stops default action.'], 'btn.addEventListener("click", e => console.log(e.target));', ['e.target', 'preventDefault', 'Event object'], 'predict_output', 'What is e.target in click handler?', 'e.target', ['Element that was clicked', 'Document', 'Window', 'null'], 'Element that was clicked'),
    makeLesson('js-int-l15', 'ClassList', 'Add/remove/toggle classes', ['element.classList.add("c"), remove("c").', 'toggle("c") adds if missing, removes if present.', 'contains("c") checks presence.'], 'el.classList.toggle("active");', ['add, remove, toggle', 'contains', 'Multiple classes'], 'fill_blank', 'Method to toggle a CSS class?', 'el.classList.___("active");', ['toggle', 'switch', 'flip', 'change'], 'toggle'),
    makeLesson('js-int-l16', 'Fetch basics', 'Get data from API', ['fetch(url) returns a Promise.', 'await fetch(url) then res.json() for JSON.', 'res.ok and res.status for errors.'], 'const res = await fetch("/api"); const data = await res.json();', ['fetch returns Promise', 'res.json()', 'res.ok'], 'predict_output', 'What does fetch return?', 'fetch(url)', ['Promise', 'Data', 'Response object', 'undefined'], 'Promise'),
    makeLesson('js-int-l17', 'LocalStorage', 'Persist in browser', ['localStorage.setItem(key, value); getItem(key).', 'Values must be strings; use JSON for objects.', 'Persists until cleared; same origin.'], 'localStorage.setItem("name", "Alice");', ['setItem, getItem', 'Strings only', 'Same origin'], 'fill_blank', 'Storage that persists until cleared?', '___ .setItem("k","v");', ['localStorage', 'sessionStorage', 'cookie', 'storage'], 'localStorage'),
];

// JS Advanced - js-adv-l8 to js-adv-l17
$additions['javascript-fundamentals-advanced'] = [
    makeLesson('js-adv-l8', 'Class syntax', 'ES6 classes', ['class Name { } with constructor, methods.', 'extends for inheritance; super() in constructor.', 'Static methods on class itself.'], 'class User { constructor(n){ this.name = n; } }', ['class, constructor', 'extends, super', 'static'], 'predict_output', 'Where does super() call?', 'class B extends A { constructor(){ super(); } }', ['Parent constructor', 'Same class', 'Window', 'Nowhere'], 'Parent constructor'),
    makeLesson('js-adv-l9', 'Private fields', '# private', ['#field is private; only inside class.', '#method() private method.', 'Not accessible from outside or subclass.'], 'class C { #secret = 1; }', ['# for private', 'Only inside class', 'Not in subclass'], 'fill_blank', 'Symbol for private class field?', 'class X { ___x = 0; }', ['#', 'private', '_', '&'], '#'),
    makeLesson('js-adv-l10', 'Generator functions', 'function* and yield', ['function* gen() { yield 1; yield 2; }.', 'Calling gen() returns iterator; .next() gets value.', 'Lazy evaluation; infinite sequences possible.'], 'function* g(){ yield 1; } g().next().value', ['function*', 'yield', 'Iterator'], 'predict_output', 'What does yield do?', 'function* f(){ yield 1; }', ['Pauses and returns value', 'Returns 1', 'Throws', 'Stops'], 'Pauses and returns value'),
    makeLesson('js-adv-l11', 'Async generators', 'async function*', ['async function* gen() { yield await fetch(); }.', 'for await (const x of gen()) to consume.', 'Streaming and pagination.'], 'async function* f(){ yield await get(); }', ['async function*', 'for await', 'Streaming'], 'fill_blank', 'Loop to consume async generator?', '___ ___ (const x of gen())', ['for await', 'await for', 'async for', 'for async'], 'for await'),
    makeLesson('js-adv-l12', 'Object.freeze & seal', 'Immutability', ['Object.freeze(obj) prevents add/delete/change.', 'Object.seal(obj) prevents add/delete but allows change.', 'Object.isFrozen(obj) checks.'], 'Object.freeze({a:1});', ['freeze immutable', 'seal no add/delete', 'isFrozen'], 'predict_output', 'Can you add property after freeze?', 'Object.freeze({}); o.x=1;', ['No', 'Yes', 'Error', 'undefined'], 'No'),
    makeLesson('js-adv-l13', 'Proxy revocable', 'Revocable proxy', ['Proxy.revocable(target, handler) returns { proxy, revoke }.', 'revoke() makes proxy unusable.', 'Use for temporary access.'], 'const { proxy, revoke } = Proxy.revocable(t, h);', ['revocable', 'revoke()', 'Temporary'], 'predict_output', 'What does revoke() do?', 'revoke()', ['Disables proxy', 'Deletes target', 'Throws', 'Nothing'], 'Disables proxy'),
    makeLesson('js-adv-l14', 'RegExp flags', 'g, i, m, s', ['g global, i ignoreCase, m multiline, s dotAll.', 'new RegExp("a", "gi") or /a/gi.', 'sticky (y) and unicode (u) too.'], '/hello/gi', ['g global', 'i ignore case', 'm multiline'], 'fill_blank', 'Flag for case-insensitive regex?', '/a/___', ['i', 'c', 'ignore', 'g'], 'i'),
    makeLesson('js-adv-l15', 'Structured clone', 'Deep clone', ['structuredClone(obj) deep clones (browser/Node).', 'Handles nested objects, arrays, Date, Map, Set.', 'Cannot clone functions or symbols.'], 'const copy = structuredClone(original);', ['structuredClone', 'Deep clone', 'No functions'], 'predict_output', 'What does structuredClone do?', 'structuredClone({a:1})', ['Deep copy', 'Shallow copy', 'Reference', 'Freeze'], 'Deep copy'),
    makeLesson('js-adv-l16', 'QueueMicrotask', 'Microtask queue', ['queueMicrotask(fn) schedules microtask.', 'Runs after current code, before next macrotask.', 'Like Promise.then but direct.'], 'queueMicrotask(() => console.log("micro"));', ['queueMicrotask', 'Microtask queue', 'Before macrotask'], 'fill_blank', 'Function to schedule microtask?', '___(() => {});', ['queueMicrotask', 'microtask', 'setMicrotask', 'Promise'], 'queueMicrotask'),
    makeLesson('js-adv-l17', 'Atomics & SharedArrayBuffer', 'Shared memory', ['SharedArrayBuffer for shared memory between workers.', 'Atomics methods for safe updates (add, store, etc.).', 'Advanced; used in parallel algorithms.'], 'Atomics.add(view, index, value);', ['SharedArrayBuffer', 'Atomics', 'Workers'], 'predict_output', 'What are Atomics for?', 'Atomics.add(...)', ['Thread-safe operations', 'Math', 'Arrays', 'Async'], 'Thread-safe operations'),
];

// PHP beginner - php-l8 to php-l17
$additions['php-development'] = [
    makeLesson('php-l8', 'GET and POST', 'Request methods', ['$_GET for URL params; $_POST for form body.', 'method="get" vs method="post" in form.', 'POST for sensitive or large data.'], '<?php $id = $_GET["id"] ?? null; ?>', ['$_GET URL', '$_POST body', 'method in form'], 'predict_output', 'Where are POST data in PHP?', '$_POST', ['Form body', 'URL', 'Cookie', 'Header'], 'Form body'),
    makeLesson('php-l9', 'If else', 'Conditionals', ['if ($x) { } elseif ($y) { } else { }.', 'Comparison: ==, ===, !=, !==, <, >.', 'Curly braces for blocks.'], '<?php if ($a > 0) { echo "pos"; } ?>', ['if elseif else', '=== strict', 'Braces'], 'fill_blank', 'Strict equality in PHP?', '$a ___ $b', ['===', '==', 'eq', '='], '==='),
    makeLesson('php-l10', 'Switch', 'Multiple branches', ['switch ($x) { case "a": break; default: }.', 'break prevents fall-through.', 'Alternative to long if-elseif.'], '<?php switch($n){ case 1: break; default: } ?>', ['switch case', 'break', 'default'], 'predict_output', 'What happens without break in switch?', 'case 1: do(); case 2:', ['Fall-through', 'Error', 'Stop', 'Nothing'], 'Fall-through'),
    makeLesson('php-l11', 'While loop', 'Condition loop', ['while ($cond) { } runs while true.', 'do { } while ($cond) runs at least once.', 'Avoid infinite loops.'], '<?php while($i < 5) { $i++; } ?>', ['while', 'do while', 'Condition'], 'fill_blank', 'Loop that runs at least once?', '___ { } while ($x);', ['do', 'while', 'loop', 'repeat'], 'do'),
    makeLesson('php-l12', 'For loop', 'Counted loop', ['for ($i=0; $i<10; $i++) { }.', 'Init; condition; increment.', 'Classic iteration.'], '<?php for($i=0;$i<3;$i++) echo $i; ?>', ['for (init;cond;inc)', 'Classic loop', 'Counter'], 'predict_output', 'How many times? for($i=0;$i<5;$i++)', 'for($i=0;$i<5;$i++)', ['5', '4', '6', '0'], '5'),
    makeLesson('php-l13', 'Multidimensional arrays', 'Arrays of arrays', ['$matrix = [[1,2],[3,4]]; $matrix[0][1] is 2.', 'Nested foreach for iteration.', 'Use for tables or trees.'], '<?php $a = [[1,2]]; echo $a[0][1]; ?>', ['Nested arrays', '[0][1] access', 'foreach nested'], 'predict_output', 'What is $a[0][0]? $a=[[5,6]]', '$a=[[5,6]]; $a[0][0]', ['5', '6', 'array', 'Error'], '5'),
    makeLesson('php-l14', 'Include path', 'Where PHP looks', ['include_path in php.ini or set_include_path().', 'include "file" looks in path.', 'get_include_path() shows current.'], '<?php set_include_path("/app"); include "lib.php"; ?>', ['include_path', 'set_include_path', 'get_include_path'], 'fill_blank', 'Function to set include path?', '___("/path");', ['set_include_path', 'include_path', 'path', 'set_path'], 'set_include_path'),
    makeLesson('php-l15', 'Return from include', 'Include returns', ['include "f.php" returns value from f.php if it has return.', 'Use for config: $config = include "config.php";.', 'Return must be at top level in included file.'], '<?php $c = include "config.php"; ?>', ['include returns', 'Config pattern', 'Top-level return'], 'predict_output', 'Can include return a value?', 'include "x.php"', ['Yes', 'No', 'Only 1', 'Only string'], 'Yes'),
    makeLesson('php-l16', 'Type juggling', 'Automatic conversion', ['PHP converts types in context: "5" + 1 is 6.', 'Strict comparison === avoids juggling.', 'Be explicit for clarity.'], '<?php echo "10" + 2; ?>', ['Type juggling', '+ converts', '=== strict'], 'predict_output', 'What is "5" + 3 in PHP?', '"5" + 3', ['8', '53', 'Error', '5'], '8'),
    makeLesson('php-l17', 'Constants', 'define and const', ['define("NAME", value); global constant.', 'const NAME = value; in class or at top level (PHP 5.3+).', 'Constants are case-sensitive by default.'], '<?php define("PI", 3.14); echo PI; ?>', ['define()', 'const keyword', 'Case-sensitive'], 'fill_blank', 'Function to define constant?', '___("MAX", 100);', ['define', 'const', 'constant', 'set'], 'define'),
];

// PHP Intermediate - php-int-l8 to php-int-l17
$additions['php-development-intermediate'] = [
    makeLesson('php-int-l8', 'Static properties', 'Class static', ['static $count; shared across instances.', 'self::$count or ClassName::$count.', 'Use for counters or shared config.'], '<?php class C { public static $n = 0; } ?>', ['static property', 'self::', 'Shared'], 'fill_blank', 'Keyword for shared class property?', 'public ___ $x = 0;', ['static', 'shared', 'class', 'common'], 'static'),
    makeLesson('php-int-l9', 'Inheritance', 'extends', ['class Child extends Parent { }.', 'Child gets public/protected of Parent.', 'override methods; parent::method() to call parent.'], '<?php class B extends A { } ?>', ['extends', 'override', 'parent::'], 'predict_output', 'What does parent::method() do?', 'parent::method()', ['Calls parent implementation', 'Creates parent', 'Deletes', 'Copies'], 'Calls parent implementation'),
    makeLesson('php-int-l10', 'Abstract classes', 'Abstract base', ['abstract class X { abstract function f(); }.', 'Cannot instantiate; must extend and implement.', 'Concrete methods allowed too.'], '<?php abstract class Base { abstract function run(); } ?>', ['abstract class', 'abstract method', 'Must extend'], 'fill_blank', 'Class that cannot be instantiated?', '___ class X { }', ['abstract', 'virtual', 'base', 'interface'], 'abstract'),
    makeLesson('php-int-l11', 'Static methods', 'Methods on class', ['public static function f() { } called as Class::f().', 'No $this in static method.', 'Use for factory or utility.'], '<?php class U { public static function id() { return 1; } } U::id(); ?>', ['static function', 'Class::method', 'No $this'], 'predict_output', 'Can static method use $this?', 'static function f() { $this->x; }', ['No', 'Yes', 'Sometimes', 'Only in PHP 8'], 'No'),
    makeLesson('php-int-l12', 'Magic methods', '__get, __set', ['__get($name), __set($name, $value) for property access.', '__isset, __unset too.', 'Overloading and proxies.'], '<?php function __get($n) { return $this->data[$n]; } ?>', ['__get __set', 'Magic methods', 'Overloading'], 'fill_blank', 'Magic method when reading property?', 'function ___($name) { }', ['__get', 'get', '__read', 'read'], '__get'),
    makeLesson('php-int-l13', 'Closures', 'Anonymous functions', ['$fn = function($x) { return $x * 2; };.', 'use ($var) to capture variable.', 'Closure object.'], '<?php $f = function($n) { return $n + 1; }; $f(2); ?>', ['function() {}', 'use ()', 'Closure'], 'predict_output', 'What does use ($x) do in closure?', 'function() use ($x) { }', ['Captures $x', 'Uses global', 'Imports', 'Nothing'], 'Captures $x'),
    makeLesson('php-int-l14', 'Arrow functions', 'Short closure (PHP 7.4+)', ['fn($x) => $x * 2 single expression.', 'fn($x) => $x + $y automatically uses $y from scope.', 'No multi-line body.'], '<?php $double = fn($x) => $x * 2; ?>', ['fn() =>', 'Single expression', 'Auto use'], 'fill_blank', 'Keyword for arrow function in PHP?', '___ ($x) => $x + 1;', ['fn', 'function', 'arrow', '=>'], 'fn'),
    makeLesson('php-int-l15', 'Variadic functions', '...$args', ['function f(...$args) { } collects rest as array.', 'Call with f(1, 2, 3); $args is [1,2,3].', 'Type hint: ...array.'], '<?php function sum(...$n) { return array_sum($n); } sum(1,2,3); ?>', ['...$args', 'Variadic', 'array_sum'], 'predict_output', 'What is $args in function f(...$args)?', 'f(1,2,3) with ...$args', ['[1,2,3]', '1', '3', 'Error'], '[1,2,3]'),
    makeLesson('php-int-l16', 'Nullable types', '?Type', ['?string means string|null.', 'Return type: function f(): ?int { }.', 'PHP 7.1+.'], '<?php function name(): ?string { return null; } ?>', ['?Type', 'Nullable', 'Return type'], 'fill_blank', 'Type for string or null?', 'function f(): ___ { }', ['?string', 'string|null', 'nullable', 'string?'], '?string'),
    makeLesson('php-int-l17', 'Match expression', 'match (PHP 8)', ['match ($x) { 1 => "a", 2 => "b", default => "?".', 'Strict comparison; single expression per arm.', 'Replaces switch for value return.'], '<?php $r = match($n) { 1 => "one", default => "many" }; ?>', ['match', 'Strict', 'default'], 'predict_output', 'Does match use strict comparison?', 'match($x) { 1 => 1 }', ['Yes', 'No', 'Optional', 'Depends'], 'Yes'),
];

// PHP Advanced - php-adv-l8 to php-adv-l17
$additions['php-development-advanced'] = [
    makeLesson('php-adv-l8', 'Enums (PHP 8.1)', 'Backed and pure enums', ['enum Color { case Red; case Blue; }.', 'Backed: enum Suit: string { case Hearts = "H"; }.', 'Enum::cases() for all cases.'], '<?php enum Status { case Active; case Done; } ?>', ['enum', 'case', 'Backed enum'], 'fill_blank', 'Keyword for enum in PHP 8.1?', '___ Status { case A; }', ['enum', 'enumeration', 'const', 'class'], 'enum'),
    makeLesson('php-adv-l9', 'Readonly properties', 'PHP 8.1', ['readonly public Type $prop; set once in constructor.', 'Cannot modify after init.', 'Promotes immutability.'], '<?php class C { public readonly string $id; } ?>', ['readonly', 'Set once', 'Constructor'], 'predict_output', 'Can readonly property be set twice?', 'readonly $x; $this->x=1; $this->x=2;', ['No', 'Yes', 'Only in constructor', 'Error'], 'No'),
    makeLesson('php-adv-l10', 'Constructor promotion', 'PHP 8', ['public function __construct(public string $name) { }.', 'Promoted params become properties automatically.', 'Less boilerplate.'], '<?php class U { public function __construct(public string $n) {} } ?>', ['Promoted params', 'public in constructor', 'Auto property'], 'fill_blank', 'Where can promotion happen?', 'function __construct(___ $x) { }', ['public', 'private', 'protected', 'var'], 'public'),
    makeLesson('php-adv-l11', 'First-class callable', 'PHP 8.1', ['$fn = $obj->method(...); captures callable.', 'Same as Closure::fromCallable([$obj, "method"]).', 'Use for passing methods.'], '<?php $f = $this->handle(...); ?>', ['... for callable', 'First-class', 'Closure'], 'predict_output', 'What does $obj->m(...) return?', '$obj->m(...)', ['Callable', 'Result of m()', 'Error', 'null'], 'Callable'),
    makeLesson('php-adv-l12', 'Named arguments', 'PHP 8', ['f(name: "A", age: 25); order does not matter.', 'Skip optional params; use for clarity.', 'Mix positional and named.'], '<?php greet(name: "Bob", greeting: "Hi"); ?>', ['Named args', 'Order free', 'Clarity'], 'fill_blank', 'PHP 8 feature for argument names?', 'f(___: "value");', ['name', 'param', 'arg', 'key'], 'name'),
    makeLesson('php-adv-l13', 'Union types', 'Type1|Type2', ['function f(int|string $x): int|null { }.', 'PHP 8.0+; multiple types allowed.', 'Intersection types with & in PHP 8.1.'], '<?php function id(int|string $x): int|string { return $x; } ?>', ['Union |', 'Multiple types', 'PHP 8'], 'predict_output', 'What does int|string mean?', 'int|string $x', ['int or string', 'both', 'array', 'null'], 'int or string'),
    makeLesson('php-adv-l14', 'Fibers', 'PHP 8.1', ['Fiber for cooperative multitasking.', 'Fiber::suspend() and resume().', 'Green threads; no parallel execution.'], '<?php $f = new Fiber(fn() => Fiber::suspend(1)); ?>', ['Fiber', 'suspend/resume', 'Cooperative'], 'fill_blank', 'PHP 8.1 feature for coroutines?', 'new ___ (fn() => ...);', ['Fiber', 'Coroutine', 'Async', 'Generator'], 'Fiber'),
    makeLesson('php-adv-l15', 'Array unpacking', 'Spread in arrays', ['$arr = [...$a, ...$b]; unpack arrays.', 'PHP 7.4+; string keys overwrite.', 'Merge with spread.'], '<?php $all = [...$first, ...$second]; ?>', ['... in array', 'Unpack', 'Merge'], 'predict_output', 'What does [...$a, ...$b] do?', '[...[1,2], ...[3,4]]', ['[1,2,3,4]', '[[1,2],[3,4]]', 'Error', '1,2,3,4'], '[1,2,3,4]'),
    makeLesson('php-adv-l16', 'Nullsafe operator', 'PHP 8.0', ['$obj?->method() returns null if $obj is null.', 'Short-chains; no need for null check.', '?-> for property too.'], '<?php $name = $user?->profile?->name; ?>', ['?->', 'Nullsafe', 'Short-circuit'], 'fill_blank', 'Nullsafe operator in PHP 8?', '$obj ___ method();', ['?->', '->?', '??->', '?.'], '?->'),
    makeLesson('php-adv-l17', 'Pattern matching', 'match arms', ['match with complex conditions (future/experimental).', 'match ($x) { 1,2 => "small"; default => "big"; }.', 'Multiple values per arm.'], '<?php match($n) { 1,2 => "low", default => "high" }; ?>', ['match multiple', 'Comma in arm', 'Strict'], 'predict_output', 'What is match(2){ 1,2=>"a" }?', 'match(2){ 1,2=>"a" }', ['a', '2', 'null', 'Error'], 'a'),
];

// SQL beginner - sql-l8 to sql-l17
$additions['sql-databases'] = [
    makeLesson('sql-l8', 'ALTER TABLE', 'Change table structure', ['ALTER TABLE t ADD COLUMN c TYPE;', 'DROP COLUMN, MODIFY COLUMN.', 'Rename table: RENAME TABLE.'], 'ALTER TABLE users ADD COLUMN phone VARCHAR(20);', ['ADD COLUMN', 'DROP COLUMN', 'MODIFY'], 'fill_blank', 'Statement to add a column?', '___ TABLE t ADD COLUMN x INT;', ['ALTER', 'ADD', 'CREATE', 'INSERT'], 'ALTER'),
    makeLesson('sql-l9', 'DROP TABLE', 'Remove table', ['DROP TABLE name; removes table and data.', 'DROP TABLE IF EXISTS name; safe drop.', 'Cannot undo.'], 'DROP TABLE IF EXISTS temp_data;', ['DROP TABLE', 'IF EXISTS', 'Permanent'], 'predict_output', 'Does DROP TABLE delete data?', 'DROP TABLE t;', ['Yes', 'No', 'Only structure', 'Asks'], 'Yes'),
    makeLesson('sql-l10', 'BETWEEN', 'Range condition', ['WHERE col BETWEEN a AND b (inclusive).', 'Same as col >= a AND col <= b.', 'Works with numbers and dates.'], 'SELECT * FROM orders WHERE total BETWEEN 10 AND 50;', ['BETWEEN inclusive', 'a AND b', 'Numbers, dates'], 'predict_output', 'Is BETWEEN inclusive?', 'x BETWEEN 1 AND 3', ['Yes', 'No', 'Left only', 'Right only'], 'Yes'),
    makeLesson('sql-l11', 'IN operator', 'Match list', ['WHERE col IN (a, b, c).', 'Shorthand for col = a OR col = b OR col = c.', 'NOT IN excludes.'], 'SELECT * FROM users WHERE status IN (\'active\', \'pending\');', ['IN (list)', 'NOT IN', 'Shorthand for OR'], 'fill_blank', 'Operator to match any of list?', 'WHERE x ___ (1,2,3)', ['IN', 'ANY', 'OR', 'MATCH'], 'IN'),
    makeLesson('sql-l12', 'IS NULL', 'Null checks', ['WHERE col IS NULL or IS NOT NULL.', '= NULL is wrong; use IS NULL.', 'Null is unknown, not zero.'], 'SELECT * FROM users WHERE email IS NULL;', ['IS NULL', 'IS NOT NULL', '= NULL wrong'], 'predict_output', 'Correct way to find NULL?', 'WHERE x = NULL', ['Wrong', 'Correct', 'Sometimes', 'Depends'], 'Wrong'),
    makeLesson('sql-l13', 'AS alias', 'Column and table aliases', ['SELECT col AS name, t AS short.', 'Alias in result set or for joins.', 'AS optional in many DBs.'], 'SELECT name AS customer_name FROM users u;', ['AS alias', 'Column and table', 'Readability'], 'fill_blank', 'Keyword for column alias?', 'SELECT id ___ user_id', ['AS', 'ALIAS', 'IS', 'TO'], 'AS'),
    makeLesson('sql-l14', 'LIMIT and OFFSET', 'Pagination', ['LIMIT n returns first n rows.', 'LIMIT n OFFSET m skips m then returns n.', 'Order by first for consistent pages.'], 'SELECT * FROM products ORDER BY id LIMIT 10 OFFSET 20;', ['LIMIT', 'OFFSET', 'Pagination'], 'predict_output', 'What does OFFSET 5 do?', 'LIMIT 10 OFFSET 5', ['Skip first 5 rows', 'Return 5', 'Skip 10', 'Nothing'], 'Skip first 5 rows'),
    makeLesson('sql-l15', 'CONCAT', 'String concatenation', ['CONCAT(a, b, c) in MySQL.', '|| in SQLite/PostgreSQL.', 'CONCAT_WS(sep, a, b) with separator.'], 'SELECT CONCAT(first_name, \' \', last_name) AS full_name;', ['CONCAT', 'CONCAT_WS', '|| in some DBs'], 'fill_blank', 'MySQL function to join strings?', 'SELECT ___(a, b);', ['CONCAT', 'JOIN', 'ADD', 'MERGE'], 'CONCAT'),
    makeLesson('sql-l16', 'COALESCE', 'Replace NULL', ['COALESCE(a, b, c) returns first non-NULL.', 'Use for default: COALESCE(col, 0).', 'Standard SQL.'], 'SELECT COALESCE(phone, \'N/A\') FROM users;', ['COALESCE', 'First non-NULL', 'Default value'], 'predict_output', 'What does COALESCE(NULL, 5) return?', 'COALESCE(NULL, 5)', ['5', 'NULL', '0', 'Error'], '5'),
    makeLesson('sql-l17', 'Comments in SQL', 'Single and multi-line', ['-- single line comment.', '/* multi-line comment */.', 'Comments ignored by engine.'], '-- Get active users\nSELECT * FROM users WHERE active = 1;', ['-- single', '/* */ multi', 'Ignored'], 'fill_blank', 'Start of single-line comment?', '___ comment', ['--', '//', '#', 'REM'], '--'),
];

// SQL Intermediate - sql-int-l8 to sql-int-l17
$additions['sql-databases-intermediate'] = [
    makeLesson('sql-int-l8', 'EXISTS', 'Existence check', ['WHERE EXISTS (SELECT 1 FROM t WHERE cond).', 'Often faster than IN for large sets.', 'Returns true if subquery returns any row.'], 'SELECT * FROM users u WHERE EXISTS (SELECT 1 FROM orders o WHERE o.user_id = u.id);', ['EXISTS', 'Subquery', 'Any row'], 'predict_output', 'When is EXISTS true?', 'EXISTS (SELECT 1 FROM t)', ['When subquery returns rows', 'When 1 exists', 'Always', 'Never'], 'When subquery returns rows'),
    makeLesson('sql-int-l9', 'Correlated subquery', 'References outer', ['Subquery references column from outer query.', 'Runs once per outer row.', 'Can be slow; consider JOIN.'], 'SELECT * FROM a WHERE (SELECT COUNT(*) FROM b WHERE b.a_id = a.id) > 5;', ['Correlated', 'Outer reference', 'Per row'], 'fill_blank', 'Subquery that uses outer column?', '___ subquery', ['Correlated', 'Nested', 'Inner', 'Linked'], 'Correlated'),
    makeLesson('sql-int-l10', 'CHECK constraint', 'Value constraint', ['CHECK (col > 0) in column or table.', 'Rejects invalid data at insert/update.', 'Not all DBs enforce (MySQL 8.0.16+).'], 'CREATE TABLE t (age INT CHECK (age >= 0));', ['CHECK', 'Validation', 'Insert/update'], 'predict_output', 'When is CHECK enforced?', 'CHECK (x > 0)', ['On insert/update', 'On select', 'Never', 'On delete'], 'On insert/update'),
    makeLesson('sql-int-l11', 'DEFAULT constraint', 'Default value', ['col TYPE DEFAULT value.', 'Used when INSERT omits column.', 'CURRENT_TIMESTAMP for dates.'], 'CREATE TABLE t (created_at DATETIME DEFAULT CURRENT_TIMESTAMP);', ['DEFAULT', 'On insert omit', 'CURRENT_TIMESTAMP'], 'fill_blank', 'Keyword for default value?', 'col INT ___ 0', ['DEFAULT', 'DEFAULT VALUE', 'SET', 'AS'], 'DEFAULT'),
    makeLesson('sql-int-l12', 'FOREIGN KEY', 'Referential integrity', ['FOREIGN KEY (col) REFERENCES other(id).', 'ON DELETE CASCADE or SET NULL.', 'Prevents orphan rows.'], 'FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE', ['FOREIGN KEY', 'REFERENCES', 'ON DELETE'], 'predict_output', 'What does ON DELETE CASCADE do?', 'ON DELETE CASCADE', ['Delete child rows', 'Prevent delete', 'Set null', 'Error'], 'Delete child rows'),
    makeLesson('sql-int-l13', 'UNIQUE constraint', 'No duplicates', ['UNIQUE on column or (col1, col2).', 'NULL allowed (multiple NULLs in some DBs).', 'Different from PRIMARY KEY.'], 'CREATE TABLE t (email VARCHAR(255) UNIQUE);', ['UNIQUE', 'No duplicates', 'NULL handling'], 'fill_blank', 'Constraint for no duplicate values?', 'email VARCHAR(100) ___', ['UNIQUE', 'DISTINCT', 'ONLY', 'SINGLE'], 'UNIQUE'),
    makeLesson('sql-int-l14', 'NULLS FIRST/LAST', 'Sort nulls', ['ORDER BY col NULLS FIRST or NULLS LAST.', 'SQL standard; MySQL uses IS NULL trick.', 'Control where nulls appear.'], 'SELECT * FROM t ORDER BY col NULLS LAST;', ['NULLS FIRST/LAST', 'Sort order', 'MySQL workaround'], 'predict_output', 'What does NULLS LAST do?', 'ORDER BY x NULLS LAST', ['Puts nulls at end', 'Excludes nulls', 'Puts nulls first', 'Error'], 'Puts nulls at end'),
    makeLesson('sql-int-l15', 'DISTINCT ON', 'PostgreSQL distinct', ['SELECT DISTINCT ON (col) ... in PostgreSQL.', 'One row per distinct col value.', 'Order by must match DISTINCT ON.'], 'SELECT DISTINCT ON (user_id) * FROM orders ORDER BY user_id, created_at DESC;', ['DISTINCT ON', 'Per group', 'PostgreSQL'], 'fill_blank', 'PostgreSQL clause for one per group?', 'SELECT ___ ON (col) ...', ['DISTINCT', 'UNIQUE', 'ONE', 'GROUP'], 'DISTINCT'),
    makeLesson('sql-int-l16', 'Lateral join', 'Reference prior FROM', ['LATERAL allows subquery to reference prior tables.', 'PostgreSQL, SQL Server (CROSS APPLY).', 'Row-by-row dependency.'], 'SELECT * FROM users u, LATERAL (SELECT * FROM orders WHERE user_id = u.id LIMIT 5) o;', ['LATERAL', 'Reference prior', 'Row dependency'], 'predict_output', 'What can LATERAL subquery use?', 'LATERAL (SELECT ... WHERE x = t.col)', ['Columns from t', 'Only constants', 'Nothing', 'All tables'], 'Columns from t'),
    makeLesson('sql-int-l17', 'Recursive CTE', 'WITH RECURSIVE', ['WITH RECURSIVE cte AS (anchor UNION ALL recursive part).', 'Anchor: base rows; recursive: reference cte.', 'Terminates when no new rows.'], 'WITH RECURSIVE n(n) AS (SELECT 1 UNION ALL SELECT n+1 FROM n WHERE n<5) SELECT * FROM n;', ['WITH RECURSIVE', 'Anchor + recursive', 'Termination'], 'fill_blank', 'CTE that references itself?', 'WITH ___ cte AS (... UNION ...)', ['RECURSIVE', 'SELF', 'REPEAT', 'LOOP'], 'RECURSIVE'),
];

// SQL Advanced - sql-adv-l8 to sql-adv-l17
$additions['sql-databases-advanced'] = [
    makeLesson('sql-adv-l8', 'FIRST_VALUE, LAST_VALUE', 'Window first/last', ['FIRST_VALUE(col) OVER (PARTITION BY x ORDER BY y).', 'LAST_VALUE needs ROWS BETWEEN or default frame.', 'Per-partition first/last.'], 'SELECT FIRST_VALUE(name) OVER (PARTITION BY dept ORDER BY salary DESC);', ['FIRST_VALUE', 'LAST_VALUE', 'Frame for LAST'], 'predict_output', 'What does FIRST_VALUE return?', 'FIRST_VALUE(x) OVER (...)', ['First in partition', 'First in table', 'Min', 'Max'], 'First in partition'),
    makeLesson('sql-adv-l9', 'NTILE', 'Bucket rows', ['NTILE(n) splits rows into n buckets.', '1 to n assigned in order.', 'Use for percentiles or equal groups.'], 'SELECT name, NTILE(4) OVER (ORDER BY score) AS quartile;', ['NTILE(n)', 'Buckets', 'Percentiles'], 'fill_blank', 'Window function for buckets?', '___ (4) OVER (...)', ['NTILE', 'BUCKET', 'GROUP', 'SPLIT'], 'NTILE'),
    makeLesson('sql-adv-l10', 'CUME_DIST', 'Cumulative distribution', ['CUME_DIST() OVER () proportion of rows <= current.', '0 to 1; same order as ORDER BY.', 'Percentile rank style.'], 'SELECT score, CUME_DIST() OVER (ORDER BY score) FROM results;', ['CUME_DIST', '0 to 1', 'Cumulative'], 'predict_output', 'What does CUME_DIST return?', 'CUME_DIST() OVER (ORDER BY x)', ['Proportion <= current', 'Rank', 'Row number', 'Percent'], 'Proportion <= current'),
    makeLesson('sql-adv-l11', 'Pivot with CASE', 'Manual pivot', ['SUM(CASE WHEN col = \'A\' THEN val ELSE 0 END) per column.', 'GROUP BY row dimension.', 'Static columns.'], 'SELECT id, SUM(CASE WHEN type=\'a\' THEN amt ELSE 0 END) AS a_amt FROM t GROUP BY id;', ['CASE in aggregate', 'Pivot', 'GROUP BY'], 'fill_blank', 'Often used with SUM for pivot?', 'SUM(___ WHEN x=1 THEN y END)', ['CASE', 'IF', 'WHEN', 'COND'], 'CASE'),
    makeLesson('sql-adv-l12', 'Full-text search', 'FULLTEXT index', ['FULLTEXT index on text columns (MySQL).', 'MATCH(col) AGAINST(\'words\').', 'Boolean mode, relevance.'], 'SELECT * FROM articles WHERE MATCH(title,body) AGAINST(\'keyword\');', ['FULLTEXT', 'MATCH AGAINST', 'Relevance'], 'predict_output', 'What is FULLTEXT for?', 'FULLTEXT index', ['Text search', 'Numbers', 'Dates', 'Joins'], 'Text search'),
    makeLesson('sql-adv-l13', 'Locking', 'FOR UPDATE', ['SELECT ... FOR UPDATE locks rows (in transaction).', 'Other transactions wait or fail.', 'Use for consistency.'], 'SELECT * FROM accounts WHERE id = 1 FOR UPDATE;', ['FOR UPDATE', 'Lock rows', 'Transaction'], 'fill_blank', 'Clause to lock selected rows?', 'SELECT * FROM t ___ UPDATE', ['FOR', 'LOCK', 'WITH', 'KEEP'], 'FOR'),
    makeLesson('sql-adv-l14', 'Replication', 'Primary-replica', ['Primary writes; replicas replicate binlog.', 'Read scaling; backup.', 'Eventually consistent.'], '-- Replication: primary + replica(s)', ['Primary-replica', 'Binlog', 'Read scaling'], 'predict_output', 'Typical use of replica?', 'Replica server', ['Read queries', 'Writes only', 'Backup only', 'None'], 'Read queries'),
    makeLesson('sql-adv-l15', 'Partitioning', 'Table partitions', ['PARTITION BY RANGE/LIST/HASH on table.', 'Splits table for performance and maintenance.', 'Transparent to queries.'], 'CREATE TABLE t (id INT) PARTITION BY RANGE (id) (...);', ['PARTITION BY', 'RANGE, LIST, HASH', 'Transparent'], 'fill_blank', 'Split table by range of values?', 'PARTITION BY ___ (col)', ['RANGE', 'LIST', 'VALUE', 'SPLIT'], 'RANGE'),
    makeLesson('sql-adv-l16', 'Soft delete', 'Deleted flag', ['Add deleted_at or is_deleted column.', 'WHERE deleted_at IS NULL in queries.', 'Restore by setting NULL/false.'], 'UPDATE users SET deleted_at = NOW() WHERE id = 1;', ['deleted_at', 'WHERE IS NULL', 'Restore'], 'predict_output', 'How to "undelete" soft-deleted row?', 'SET deleted_at = NULL', ['Set column to NULL', 'DELETE again', 'Cannot', 'ROLLBACK'], 'Set column to NULL'),
    makeLesson('sql-adv-l17', 'Pagination best practices', 'Keyset vs offset', ['OFFSET slow on large tables (scans then skip).', 'Keyset: WHERE id > last_id ORDER BY id LIMIT n.', 'Stable and faster.'], 'SELECT * FROM t WHERE id > 100 ORDER BY id LIMIT 20;', ['Keyset pagination', 'id > last', 'Avoid OFFSET'], 'fill_blank', 'Faster than OFFSET for big tables?', 'WHERE id ___ last_id LIMIT n', ['>', '>=', 'OFFSET', 'SKIP'], '>'),
];

// CSS beginner - css-l8 to css-l17
$additions['css-styling'] = [
    makeLesson('css-l8', 'Display property', 'block, inline, none', ['display: block; inline; inline-block; none.', 'inline-block: inline flow, block box.', 'none removes from layout.'], 'display: inline-block;', ['block, inline', 'inline-block', 'none'], 'predict_output', 'What does display: none do?', 'display: none', ['Removes from layout', 'Hides visually', 'Same as hidden', 'Shows'], 'Removes from layout'),
    makeLesson('css-l9', 'Width and height', 'Sizing elements', ['width, height in px, %, em, rem.', 'max-width, min-width for fluid.', 'box-sizing affects total size.'], 'width: 100%; max-width: 1200px;', ['width, height', 'max/min', 'box-sizing'], 'fill_blank', 'Property to limit max width?', '___-width: 800px;', ['max', 'maximum', 'cap', 'limit'], 'max'),
    makeLesson('css-l10', 'Margin and padding', 'Spacing', ['margin: outside border; padding: inside.', 'Shorthand: 1 value all, 2 value V H, 4 value T R B L.', 'margin: auto centers block.'], 'margin: 10px 20px; padding: 5px;', ['margin outside', 'padding inside', 'auto center'], 'predict_output', 'What does margin: auto do on block?', 'margin: auto', ['Centers horizontally', 'Centers both', 'No effect', 'Full width'], 'Centers horizontally'),
    makeLesson('css-l11', 'Background', 'Colors and images', ['background-color, background-image: url().', 'background-size: cover/contain; position; repeat.', 'Shorthand: background: color url() position/size repeat.'], 'background: #fff url(bg.jpg) center/cover no-repeat;', ['color, image', 'size, position', 'Shorthand'], 'fill_blank', 'Value to cover whole area?', 'background-size: ___;', ['cover', 'full', '100%', 'fill'], 'cover'),
    makeLesson('css-l12', 'Links and cursor', 'Link states', ['a:link, :visited, :hover, :active.', 'cursor: pointer; default; not-allowed.', 'Order matters for link states.'], 'a:hover { color: blue; } cursor: pointer;', [':link :visited :hover :active', 'cursor', 'Order'], 'predict_output', 'Cursor for clickable?', 'cursor: pointer', ['Hand pointer', 'Arrow', 'Text', 'Default'], 'Hand pointer'),
    makeLesson('css-l13', 'Lists styling', 'list-style', ['list-style-type: disc/circle/none/decimal.', 'list-style-position: inside/outside.', 'list-style-image: url().'], 'list-style: none;', ['list-style-type', 'position', 'image'], 'fill_blank', 'Remove list bullets?', 'list-style: ___;', ['none', 'no', 'hide', 'remove'], 'none'),
    makeLesson('css-l14', 'Tables styling', 'Border collapse', ['border-collapse: collapse; single borders.', 'border-spacing for separate.', 'table-layout: fixed for equal columns.'], 'table { border-collapse: collapse; }', ['border-collapse', 'border-spacing', 'table-layout'], 'predict_output', 'What does border-collapse do?', 'border-collapse: collapse', ['Single shared borders', 'No borders', 'Thick borders', 'Hidden'], 'Single shared borders'),
    makeLesson('css-l15', 'Overflow', 'Handle overflow', ['overflow: visible/hidden/scroll/auto.', 'overflow-x, overflow-y for axes.', 'scroll adds scrollbars; auto when needed.'], 'overflow: auto;', ['visible, hidden', 'scroll, auto', 'x and y'], 'fill_blank', 'Overflow that adds scrollbar when needed?', 'overflow: ___;', ['auto', 'scroll', 'visible', 'hidden'], 'auto'),
    makeLesson('css-l16', 'Visibility', 'visible and hidden', ['visibility: visible/hidden/collapse.', 'hidden keeps space; display:none does not.', 'collapse for table rows/columns.'], 'visibility: hidden;', ['visible, hidden', 'Keeps space', 'collapse'], 'predict_output', 'Does visibility: hidden keep space?', 'visibility: hidden', ['Yes', 'No', 'Sometimes', 'Depends'], 'Yes'),
    makeLesson('css-l17', 'Opacity', 'Transparency', ['opacity: 0 to 1; affects element and children.', 'For background only use rgba/hsla.', 'opacity: 0 still receives events.'], 'opacity: 0.5;', ['opacity 0-1', 'rgba for bg only', 'Events'], 'fill_blank', 'Property for element transparency?', '___: 0.5;', ['opacity', 'transparent', 'alpha', 'visibility'], 'opacity'),
];

// CSS Intermediate - css-int-l8 to css-int-l17
$additions['css-styling-intermediate'] = [
    makeLesson('css-int-l8', 'Grid areas', 'Named grid areas', ['grid-template-areas: "a b" "c d";', 'grid-area: a; on child.', 'Visual layout map.'], 'grid-template-areas: "header header" "main aside";', ['template-areas', 'grid-area', 'Named'], 'fill_blank', 'Property for named grid regions?', 'grid-___-areas: "a b";', ['template', 'area', 'name', 'region'], 'template'),
    makeLesson('css-int-l9', 'Animation fill mode', 'animation-fill-mode', ['forwards keeps end state; backwards applies start.', 'both: backwards + forwards.', 'none (default): no hold.'], 'animation-fill-mode: forwards;', ['forwards', 'backwards', 'both'], 'predict_output', 'What does fill-mode: forwards do?', 'animation-fill-mode: forwards', ['Keeps end state', 'Repeats', 'Pauses', 'Resets'], 'Keeps end state'),
    makeLesson('css-int-l10', 'Transform origin', 'Pivot point', ['transform-origin: x y; (e.g. center, 50% 50%).', 'Affects rotate, scale pivot.', 'Default center.'], 'transform-origin: top left;', ['transform-origin', 'Pivot', 'center, top, left'], 'fill_blank', 'Property to set transform pivot?', 'transform-___: center;', ['origin', 'pivot', 'point', 'center'], 'origin'),
    makeLesson('css-int-l11', 'Will-change', 'Optimization hint', ['will-change: transform; hints browser.', 'Use sparingly; remove after animation.', 'Can create new layer.'], 'will-change: transform;', ['will-change', 'Hint', 'Use sparingly'], 'predict_output', 'What is will-change for?', 'will-change: transform', ['Performance hint', 'Required for transform', 'Disables transform', 'Nothing'], 'Performance hint'),
    makeLesson('css-int-l12', 'Backface visibility', '3D flip', ['backface-visibility: hidden on flip cards.', 'Prevents reverse side showing during flip.', 'Used with transform: rotateY.'], 'backface-visibility: hidden;', ['backface-visibility', '3D', 'hidden'], 'fill_blank', 'Property to hide back of rotated element?', '___-visibility: hidden;', ['backface', 'back', 'reverse', 'flip'], 'backface'),
    makeLesson('css-int-l13', 'Scroll behavior', 'Smooth scroll', ['scroll-behavior: smooth on container.', 'Scrolls to anchor/scrollTo smoothly.', 'Native smooth scroll.'], 'html { scroll-behavior: smooth; }', ['scroll-behavior', 'smooth', 'Anchor links'], 'predict_output', 'What does scroll-behavior: smooth do?', 'scroll-behavior: smooth', ['Smooth scroll to target', 'Slower scroll', 'No scroll', 'Animate page'], 'Smooth scroll to target'),
    makeLesson('css-int-l14', 'Gap property', 'Flex and grid gap', ['gap: size; in flex and grid.', 'row-gap, column-gap for separate.', 'No margin collapse issues.'], 'display: flex; gap: 16px;', ['gap', 'row-gap', 'column-gap'], 'fill_blank', 'Property for space between flex/grid items?', '___: 1rem;', ['gap', 'space', 'margin', 'padding'], 'gap'),
    makeLesson('css-int-l15', 'Aspect-ratio', 'Maintain ratio', ['aspect-ratio: 16/9 or 1.', 'Box keeps ratio when one dimension set.', 'Replaces padding hack.'], 'aspect-ratio: 16 / 9;', ['aspect-ratio', '16/9', 'No padding hack'], 'predict_output', 'What does aspect-ratio: 1 do?', 'aspect-ratio: 1', ['Square', 'Circle', 'Full width', 'Nothing'], 'Square'),
    makeLesson('css-int-l16', 'Object-fit', 'Image in box', ['object-fit: fill/contain/cover/none.', 'On img/video; how content fits box.', 'cover: fill box, crop; contain: fit, letterbox.'], 'object-fit: cover;', ['object-fit', 'cover, contain', 'img, video'], 'fill_blank', 'Fit image to box without distortion?', 'object-___: cover;', ['fit', 'size', 'scale', 'fill'], 'fit'),
    makeLesson('css-int-l17', 'Filter property', 'Blur, brightness', ['filter: blur(5px); brightness(1.2); grayscale(1).', 'Multiple filters space-separated.', 'GPU-accelerated.'], 'filter: blur(2px) brightness(1.1);', ['filter', 'blur, brightness', 'Multiple'], 'predict_output', 'What does filter: blur(2px) do?', 'filter: blur(2px)', ['Blurs element', 'Blurs background', 'Shadow', 'Nothing'], 'Blurs element'),
];

// CSS Advanced - css-adv-l8 to css-adv-l17
$additions['css-styling-advanced'] = [
    makeLesson('css-adv-l8', 'Scroll snap', 'Snap scroll', ['scroll-snap-type: y mandatory; on container.', 'scroll-snap-align: start/center on children.', 'Panels snap into place.'], 'scroll-snap-type: y mandatory; scroll-snap-align: start;', ['scroll-snap-type', 'scroll-snap-align', 'mandatory'], 'fill_blank', 'Property to snap scroll position?', 'scroll-snap-___: start;', ['align', 'type', 'position', 'snap'], 'align'),
    makeLesson('css-adv-l9', 'Mix-blend-mode', 'Blend elements', ['mix-blend-mode: multiply; screen; overlay.', 'Blends with backdrop.', 'Creative effects.'], 'mix-blend-mode: multiply;', ['mix-blend-mode', 'multiply, screen', 'Backdrop'], 'predict_output', 'What does mix-blend-mode do?', 'mix-blend-mode: overlay', ['Blends with behind', 'Opacity', 'Filter', 'Nothing'], 'Blends with behind'),
    makeLesson('css-adv-l10', 'Mask image', 'CSS masking', ['mask-image: url(); mask-size; mask-position.', 'Alpha of mask shows/hides element.', 'SVG or gradient mask.'], 'mask-image: linear-gradient(black, transparent);', ['mask-image', 'Alpha mask', 'Gradient mask'], 'fill_blank', 'Property for image mask?', '___-image: url(mask.png);', ['mask', 'clip', 'hide', 'alpha'], 'mask'),
    makeLesson('css-adv-l11', 'Scrollbar styling', 'Custom scrollbar', ['::-webkit-scrollbar, ::-webkit-scrollbar-thumb.', 'scrollbar-width: thin; scrollbar-color (Firefox).', 'WebKit prefix for Chrome/Safari.'], '::-webkit-scrollbar { width: 8px; }', ['::-webkit-scrollbar', 'scrollbar-width', 'Firefox'], 'predict_output', 'Pseudoelement for scrollbar track?', '::-webkit-scrollbar', ['Scrollbar track/thumb', 'Scrollbar only', 'Scroll area', 'None'], 'Scrollbar track/thumb'),
    makeLesson('css-adv-l12', '@layer', 'Cascade layers', ['@layer base, components, utilities;', 'Order of layers overrides source order.', 'Control cascade explicitly.'], '@layer base, components; @layer base { }', ['@layer', 'Cascade', 'Order'], 'fill_blank', 'At-rule for cascade layers?', '@___ base, comp;', ['layer', 'cascade', 'order', 'priority'], 'layer'),
    makeLesson('css-adv-l13', '@scope', 'Scoped styles', ['@scope (.card) { } limits to within .card.', 'Newer spec; limited support.', 'Replaces need for BEM in scope.'], '@scope (.card) { .title { } }', ['@scope', 'Limit scope', 'New spec'], 'predict_output', 'What does @scope do?', '@scope (.x) { p { } }', ['Limits p to inside .x', 'Global p', 'Nothing', 'Error'], 'Limits p to inside .x'),
    makeLesson('css-adv-l14', 'Anchor positioning', 'Popover position', ['anchor-name: --pop; position: absolute; inset: anchor(...).', 'Position relative to anchor element.', 'New CSS anchor spec.'], 'anchor-name: --btn; position: absolute; inset: anchor(top);', ['anchor-name', 'anchor()', 'Popover'], 'fill_blank', 'Function for anchor-based position?', 'inset: ___(top);', ['anchor', 'var', 'anchor-position', 'ref'], 'anchor'),
    makeLesson('css-adv-l15', 'View transitions', 'Animate page change', ['document.startViewTransition(callback) for SPA.', '::view-transition-old/new pseudo-elements.', 'Smooth transition between states.'], 'document.startViewTransition(() => updateDOM());', ['startViewTransition', 'View transition', 'SPA'], 'predict_output', 'What do view transitions animate?', 'startViewTransition', ['DOM state change', 'Scroll', 'Load', 'Click'], 'DOM state change'),
    makeLesson('css-adv-l16', 'Subgrid', 'Grid in grid', ['grid-template-rows: subgrid; child inherits parent tracks.', 'Alignment across nested grids.', 'Limited support.'], 'grid-template-rows: subgrid;', ['subgrid', 'Inherit tracks', 'Alignment'], 'fill_blank', 'Value to inherit parent grid tracks?', 'grid-template-rows: ___;', ['subgrid', 'inherit', 'parent', 'same'], 'subgrid'),
    makeLesson('css-adv-l17', '@property', 'Custom properties with type', ['@property --name { syntax: "<color>"; inherits: true; }.', 'Enables interpolation of custom props.', 'Smooth gradient animation.'], '@property --hue { syntax: "<number>"; inherits: true; initial-value: 0; }', ['@property', 'syntax', 'Interpolation'], 'predict_output', 'What does @property enable?', '@property --x { syntax: "<number>"; }', ['Typed custom prop', 'New variable', 'Constant', 'Nothing'], 'Typed custom prop'),
];

foreach ($modules as &$module) {
    $id = $module['id'];
    if (!isset($additions[$id])) {
        continue;
    }
    $module['lessons'] = array_merge($module['lessons'], $additions[$id]);
    $totalXp = 0;
    foreach ($module['lessons'] as $lesson) {
        $totalXp += (int) ($lesson['xp'] ?? 50);
    }
    $module['total_xp'] = $totalXp;
}

$out = json_encode($modules, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
if ($out === false) {
    die("JSON encode failed\n");
}
file_put_contents($path, $out);
echo "Added 10 more lessons to each of the 15 modules. Total lessons per module now 17, total_xp 850.\n";
