<?php
/**
 * One-time script: Add more lessons to each module and make each difficulty
 * have DIFFERENT lessons (no duplicate content between beginner/intermediate/advanced).
 * Run from project root: php update_modules_lessons.php
 */

$path = __DIR__ . '/data/modules.json';
$json = file_get_contents($path);
$modules = json_decode($json, true);
if (!is_array($modules)) {
    die("Failed to load modules.json\n");
}

// ─── New lessons per topic & difficulty (unique content) ───

$extraLessons = [
    'html-basics' => [
        [
            'id' => 'html-l4',
            'title' => 'Tables & iframes',
            'content' => 'Display tabular data and embed external content',
            'details' => [
                'Tables use <table>, <tr> (row), <th> (header cell), <td> (data cell).',
                '<thead>, <tbody>, <tfoot> group rows for semantics and styling.',
                'colspan and rowspan merge cells: <td colspan="2"> spans two columns.',
                '<iframe src="url"> embeds another page or video (e.g. YouTube).',
                'Hint: The correct tag for a table header cell is <th> - it makes content bold and semantic for screen readers.'
            ],
            'example_code' => "<table>\n  <tr><th>Name</th><th>Score</th></tr>\n  <tr><td>Alice</td><td>95</td></tr>\n</table>",
            'key_points' => ['<table>, <tr>, <th>, <td>', 'colspan/rowspan merge cells', '<iframe> embeds external content'],
            'xp' => 50,
            'game' => ['type' => 'fill_blank', 'question' => 'Which tag defines a table header cell?', 'code_template' => '<tr><___>Name</___></tr>', 'options' => ['<th>', '<td>', '<header>', '<head>'], 'answer' => '<th>']
        ],
        [
            'id' => 'html-l5',
            'title' => 'Meta tags & SEO basics',
            'content' => 'Improve discoverability with meta and title',
            'details' => [
                '<title> appears in the browser tab and search results - keep it unique per page.',
                '<meta charset="UTF-8"> declares character encoding (use in <head>).',
                '<meta name="description" content="..."> is used by search engines for snippets.',
                'Viewport meta: <meta name="viewport" content="width=device-width, initial-scale=1"> for responsive design.',
                'Hint: The tag that sets the text in the browser tab is <title>.'
            ],
            'example_code' => "<head>\n  <meta charset=\"UTF-8\">\n  <meta name=\"viewport\" content=\"width=device-width\">\n  <title>My Page</title>\n</head>",
            'key_points' => ['<title> for tab and SEO', 'meta charset and viewport', 'meta description for search snippets'],
            'xp' => 50,
            'game' => ['type' => 'fill_blank', 'question' => 'Which tag sets the text shown in the browser tab?', 'code_template' => '<___>Welcome to my site</___>', 'options' => ['title', 'head', 'tab', 'meta'], 'answer' => 'title']
        ],
    ],
    'html-basics-intermediate' => [
        ['id' => 'html-int-l1', 'title' => 'Data attributes & custom data', 'content' => 'Store extra data on elements with data-* attributes', 'details' => ['data-* attributes store custom data: data-id="5", data-status="active".', 'Access in JavaScript: element.dataset.id or getAttribute("data-id").', 'Use for config, state, or passing values to scripts without extra markup.', 'Names become camelCase in JS: data-user-name → dataset.userName.'], 'example_code' => '<div data-id="42" data-role="card">Card</div>', 'key_points' => ['data-* for custom attributes', 'dataset in JavaScript', 'Use for config and state'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'What prefix do custom data attributes use?', 'code_template' => '<div ___user-id="123">', 'options' => ['data-', 'data', 'custom-', 'attr-'], 'answer' => 'data-']],
        ['id' => 'html-int-l2', 'title' => 'ARIA basics for accessibility', 'content' => 'Make dynamic content accessible with ARIA', 'details' => ['ARIA (Accessible Rich Internet Applications) adds roles and labels for screen readers.', 'role="button", role="navigation", role="alert" describe widget type.', 'aria-label gives a short name: <button aria-label="Close">×</button>.', 'aria-hidden="true" hides decorative elements from assistive tech.'], 'example_code' => '<nav aria-label="Main">...</nav>\n<button aria-label="Close dialog">×</button>', 'key_points' => ['role describes widget type', 'aria-label for names', 'aria-hidden for decorative'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Which attribute gives a short name for screen readers?', 'code_template' => '<button ___="Close">×</button>', 'options' => ['aria-label', 'title', 'alt', 'label'], 'answer' => 'aria-label']],
        ['id' => 'html-int-l3', 'title' => 'Responsive images with srcset', 'content' => 'Serve the right image size for each device', 'details' => ['<img srcset="small.jpg 480w, large.jpg 1024w" sizes="..."> lets the browser pick.', 'sizes tells the browser how wide the image will display (e.g. 100vw or 50vw).', 'picture + source can swap entire image (e.g. WebP vs PNG).', 'Reduces bandwidth and improves load time on mobile.'], 'example_code' => '<img src="fallback.jpg" srcset="small.jpg 480w, large.jpg 1024w" sizes="100vw" alt="Photo">', 'key_points' => ['srcset for multiple resolutions', 'sizes for display width', 'picture for art direction'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What does srcset help the browser choose?', 'code' => '<img srcset="a.jpg 400w, b.jpg 800w" sizes="50vw">', 'options' => ['Image size to download', 'Image format', 'Image position', 'Image alt text'], 'answer' => 'Image size to download']],
        ['id' => 'html-int-l4', 'title' => 'Details & Summary', 'content' => 'Native expand/collapse without JavaScript', 'details' => ['<details> and <summary> create a native disclosure widget.', '<summary> is the clickable heading; the rest of <details> is the content.', 'Add open attribute to show expanded by default.', 'Use for FAQs, optional sections, or collapsible panels.'], 'example_code' => "<details>\n  <summary>Click to expand</summary>\n  <p>Hidden content here.</p>\n</details>", 'key_points' => ['<details> and <summary>', 'No JavaScript needed', 'open for default expanded'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Which tag is the clickable part of a details block?', 'code_template' => '<details><___>Show more</___>...</details>', 'options' => ['summary', 'header', 'title', 'label'], 'answer' => 'summary']],
        ['id' => 'html-int-l5', 'title' => 'HTML5 APIs overview', 'content' => 'Introduction to browser APIs', 'details' => ['LocalStorage and sessionStorage store key-value data in the browser.', 'Geolocation API: navigator.geolocation.getCurrentPosition().', 'Canvas API allows drawing 2D graphics with JavaScript.', 'These are accessed via JavaScript, not HTML tags alone.'], 'example_code' => '// In JS: localStorage.setItem("key", "value");\n// document.querySelector("canvas").getContext("2d");', 'key_points' => ['localStorage for persistence', 'Geolocation for location', 'Canvas for 2D drawing'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'Where is data stored when using localStorage?', 'code' => 'localStorage.setItem("name", "Alice");', 'options' => ['In the browser', 'On the server', 'In a cookie only', 'In HTML'], 'answer' => 'In the browser']],
    ],
    'html-basics-advanced' => [
        ['id' => 'html-adv-l1', 'title' => 'Custom data & microdata', 'content' => 'Structured data for search engines', 'details' => ['Microdata uses itemscope, itemtype, itemprop to mark up structured data.', 'Schema.org types (e.g. Person, Product) help search engines understand content.', 'Google can show rich results (e.g. ratings, prices) from microdata.', 'JSON-LD is an alternative: script type="application/ld+json".'], 'example_code' => '<div itemscope itemtype="https://schema.org/Person">\n  <span itemprop="name">Alice</span>\n</div>', 'key_points' => ['itemscope, itemtype, itemprop', 'Schema.org vocabulary', 'JSON-LD alternative'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Which attribute defines the type of structured data?', 'code_template' => '<div itemscope ___="https://schema.org/Product">', 'options' => ['itemtype', 'itemscope', 'itemprop', 'schema'], 'answer' => 'itemtype']],
        ['id' => 'html-adv-l2', 'title' => 'Security: XSS & CSP', 'content' => 'Reduce XSS risk with safe practices', 'details' => ['XSS (Cross-Site Scripting) happens when user input is output as HTML/script.', 'Always escape output: use htmlspecialchars() in PHP or textContent in JS.', 'Content-Security-Policy (CSP) header restricts where scripts and styles can load.', 'Avoid innerHTML with user data; prefer safe APIs or templating.'], 'example_code' => '<!-- Safe: escape user input -->\n<p><?= htmlspecialchars($userInput) ?></p>', 'key_points' => ['Escape all user output', 'CSP limits script sources', 'Prefer textContent over innerHTML'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What does CSP (Content-Security-Policy) control?', 'code' => 'Content-Security-Policy: default-src \'self\'', 'options' => ['Where scripts can load from', 'Password strength', 'Database access', 'Cookie expiry'], 'answer' => 'Where scripts can load from']],
        ['id' => 'html-adv-l3', 'title' => 'Accessibility audit', 'content' => 'Check and fix accessibility issues', 'details' => ['Use semantic HTML first: main, nav, article, section, header, footer.', 'Ensure keyboard focus order and visible focus styles.', 'Images need meaningful alt text; decorative images alt="".', 'Color contrast ratios (WCAG): 4.5:1 for normal text, 3:1 for large.'], 'example_code' => '<main>\n  <nav aria-label="Main">...</nav>\n  <article>...</article>\n</main>', 'key_points' => ['Semantic HTML', 'Keyboard and focus', 'Alt text and contrast'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Decorative images should use alt equal to?', 'code_template' => '<img src="decoration.png" alt="___">', 'options' => ['""', '"decoration"', '"image"', 'none'], 'answer' => '""']],
        ['id' => 'html-adv-l4', 'title' => 'Template & slot', 'content' => 'Reusable markup with template and slot', 'details' => ['<template> holds HTML that is not rendered until cloned via JavaScript.', 'Web Components can use <slot> to inject content into a custom element.', 'Slots let the consumer pass markup into predefined places.', 'Use with customElements.define() for reusable components.'], 'example_code' => '<template id="card-tpl">\n  <div class="card"><slot name="title"></slot></div>\n</template>', 'key_points' => ['<template> for inert markup', '<slot> in custom elements', 'Clone and use in JS'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'When is the content inside <template> rendered?', 'code' => '<template><p>Hello</p></template>', 'options' => ['When cloned/used in JS', 'Immediately', 'On click', 'Never'], 'answer' => 'When cloned/used in JS']],
        ['id' => 'html-adv-l5', 'title' => 'Performance: lazy loading', 'content' => 'Faster pages with lazy loading', 'details' => ['loading="lazy" on images defers loading until near viewport: <img loading="lazy">.', 'iframe loading="lazy" defers iframe load until needed.', 'Reduces initial payload and improves LCP (Largest Contentful Paint).', 'Native; no JavaScript required for basic lazy images.'], 'example_code' => '<img src="hero.jpg" alt="Hero" loading="lazy">\n<img src="below-fold.jpg" alt="Below" loading="lazy">', 'key_points' => ['loading="lazy" on img/iframe', 'Better initial load', 'Native browser support'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Which attribute defers image load until near viewport?', 'code_template' => '<img src="x.jpg" ___="lazy">', 'options' => ['loading', 'defer', 'lazy', 'delay'], 'answer' => 'loading']],
    ],
];

// JavaScript extra lessons (beginner: add 2; intermediate/advanced: replace with 5 each)
$jsBeginnerExtra = [
    ['id' => 'js-l4', 'title' => 'Conditionals: if & else', 'content' => 'Control flow with conditions', 'details' => ['if (condition) { } runs code only when the condition is true.', 'else runs when the if condition is false.', 'Use === for strict equality (type + value); avoid ==.', 'Logical operators: && (and), || (or), ! (not).'], 'example_code' => "let age = 20;\nif (age >= 18) {\n  console.log('Adult');\n} else {\n  console.log('Minor');\n}", 'key_points' => ['if/else for branching', '=== for strict equality', '&&, ||, ! for logic'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What is logged?', 'code' => "let x = 10; if (x > 5) { console.log('Yes'); } else { console.log('No'); }", 'options' => ['Yes', 'No', 'undefined', 'Error'], 'answer' => 'Yes']],
    ['id' => 'js-l5', 'title' => 'Loops: for and while', 'content' => 'Repeat actions with loops', 'details' => ['for (let i = 0; i < 5; i++) { } runs 5 times.', 'while (condition) { } runs until condition is false.', 'break exits the loop; continue skips to the next iteration.', 'Avoid infinite loops: ensure condition eventually becomes false.'], 'example_code' => "for (let i = 0; i < 3; i++) {\n  console.log(i);\n}\n// 0, 1, 2", 'key_points' => ['for for counted loops', 'while for condition-based', 'break and continue'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'How many times does this loop run?', 'code' => "for (let i = 0; i < 4; i++) { }", 'options' => ['4', '3', '5', '0'], 'answer' => '4']],
];
$jsIntermediate = [
    ['id' => 'js-int-l1', 'title' => 'Closures', 'content' => 'Functions that remember their scope', 'details' => ['A closure is a function that keeps access to variables from its outer scope.', 'Inner function can read/update variables from the enclosing function.', 'Use for private state, callbacks, and factories.'], 'example_code' => "function makeCounter() {\n  let count = 0;\n  return () => ++count;\n}\nconst c = makeCounter(); c(); c(); // 1, 2", 'key_points' => ['Inner function keeps outer scope', 'Private state', 'Callbacks and factories'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What does c() return the second time?', 'code' => "let n=0; const c=()=>++n; c(); c();", 'options' => ['2', '1', '0', 'undefined'], 'answer' => '2']],
    ['id' => 'js-int-l2', 'title' => 'Promises & async/await', 'content' => 'Handle asynchronous operations', 'details' => ['Promises represent a value that may be available later: new Promise((resolve, reject) => {}).', 'async function f() { await promise; } pauses until the promise settles.', 'Use try/catch with async/await for error handling.', 'fetch() returns a Promise; await fetch(url) then await res.json().'], 'example_code' => "async function getData() {\n  const res = await fetch('/api');\n  return res.json();\n}", 'key_points' => ['Promises for async', 'async/await syntax', 'try/catch with await'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Keyword to wait for a Promise inside async function?', 'code_template' => 'async function f() { const d = ___ fetch(url); }', 'options' => ['await', 'async', 'then', 'wait'], 'answer' => 'await']],
    ['id' => 'js-int-l3', 'title' => 'DOM manipulation', 'content' => 'Change the page with JavaScript', 'details' => ['document.querySelector(selector) returns the first matching element.', 'element.textContent and element.innerHTML set content.', 'element.addEventListener("click", handler) attaches event listeners.', 'createElement, appendChild, removeChild build and modify the tree.'], 'example_code' => "const btn = document.querySelector('#btn');\nbtn.addEventListener('click', () => btn.textContent = 'Clicked');", 'key_points' => ['querySelector/querySelectorAll', 'textContent vs innerHTML', 'addEventListener'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What does querySelector return if nothing matches?', 'code' => "document.querySelector('.missing')", 'options' => ['null', 'undefined', '[]', '0'], 'answer' => 'null']],
    ['id' => 'js-int-l4', 'title' => 'Destructuring', 'content' => 'Unpack arrays and objects easily', 'details' => ['const [a, b] = [1, 2]; assigns a=1, b=2.', 'const { name, age } = user; pulls name and age from user.', 'Default values: const { x = 0 } = obj;', 'Rest: const [first, ...rest] = arr;'], 'example_code' => "const [x, y] = [10, 20];\nconst { name } = { name: 'Alice', age: 25 };", 'key_points' => ['Array and object destructuring', 'Defaults and rest'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What is a after: const [a,b] = [5,10];', 'code' => "const [a,b] = [5,10];", 'options' => ['5', '10', '[5,10]', 'undefined'], 'answer' => '5']],
    ['id' => 'js-int-l5', 'title' => 'Modules: import & export', 'content' => 'Split code into modules', 'details' => ['export const x = 1; or export default function f() {} to export.', 'import { x } from "./file.js"; or import f from "./file.js"; to import.', 'ES modules run in strict mode and have their own scope.', 'Browsers need script type="module" for import/export.'], 'example_code' => "// math.js\nexport const add = (a,b) => a+b;\n// main.js\nimport { add } from './math.js';", 'key_points' => ['export / import', 'Named vs default export', 'type="module" in script'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Keyword to export a constant from a module?', 'code_template' => '___ const PI = 3.14;', 'options' => ['export', 'import', 'module', 'extern'], 'answer' => 'export']],
];
$jsAdvanced = [
    ['id' => 'js-adv-l1', 'title' => 'Prototypes & inheritance', 'content' => 'How JavaScript objects inherit', 'details' => ['Objects have a hidden [[Prototype]]; __proto__ or Object.getPrototypeOf().', 'Constructor functions and class extend set up the prototype chain.', 'Methods on the prototype are shared; properties on this are per instance.'], 'example_code' => "function Person(n){ this.name = n; }\nPerson.prototype.greet = function(){ return this.name; };", 'key_points' => ['Prototype chain', 'Shared methods on prototype', 'class extends'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'Where are shared methods typically attached?', 'code' => "Person.prototype.sayHi = function(){}", 'options' => ['On the prototype', 'On each instance', 'On window', 'On class'], 'answer' => 'On the prototype']],
    ['id' => 'js-adv-l2', 'title' => 'Event loop & concurrency', 'content' => 'How async code runs', 'details' => ['Single-threaded: one call stack; long tasks block the thread.', 'Callbacks, Promises, and microtasks run after the current stack.', 'setTimeout(fn, 0) defers to the next tick of the event loop.', 'async/await still uses the same event loop; no extra threads.'], 'example_code' => "console.log(1);\nsetTimeout(() => console.log(2), 0);\nPromise.resolve().then(() => console.log(3));\nconsole.log(4);\n// 1, 4, 3, 2", 'key_points' => ['Single-threaded', 'Microtasks before macrotasks', 'setTimeout vs Promise'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What runs first: setTimeout(0) or Promise.then?', 'code' => "setTimeout(()=>{},0); Promise.resolve().then(()=>{});", 'options' => ['Promise.then', 'setTimeout', 'Same time', 'Depends'], 'answer' => 'Promise.then']],
    ['id' => 'js-adv-l3', 'title' => 'Error handling & debugging', 'content' => 'Robust error handling', 'details' => ['try { } catch (e) { } finally { } for synchronous errors.', 'throw new Error("message") to create errors.', 'Custom errors: class MyError extends Error { }.', 'Use breakpoints and console in DevTools; avoid console.log in production.'], 'example_code' => "try {\n  JSON.parse('invalid');\n} catch (e) {\n  console.error(e.message);\n}", 'key_points' => ['try/catch/finally', 'throw and Error', 'Custom error classes'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Block that runs after try/catch regardless?', 'code_template' => 'try { } catch(e) { } ___ { cleanup(); }', 'options' => ['finally', 'after', 'then', 'end'], 'answer' => 'finally']],
    ['id' => 'js-adv-l4', 'title' => 'WeakMap & WeakSet', 'content' => 'Memory-friendly collections', 'details' => ['WeakMap keys are objects only; entries can be garbage-collected when key is unused.', 'WeakSet holds only objects; same weak reference behavior.', 'Use when you want to attach data to objects without preventing GC.', 'No size property or iteration; keys must be objects.'], 'example_code' => "const wm = new WeakMap();\nconst obj = {};\nwm.set(obj, 'metadata');\nwm.get(obj); // 'metadata'", 'key_points' => ['Keys are objects only', 'Allow GC when key unused', 'No size or iteration'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What can be a key in WeakMap?', 'code' => "new WeakMap()", 'options' => ['Only objects', 'Any value', 'Strings', 'Numbers'], 'answer' => 'Only objects']],
    ['id' => 'js-adv-l5', 'title' => 'Proxies & Reflect', 'content' => 'Meta-programming with Proxy', 'details' => ['new Proxy(target, handler) intercepts property access and mutations.', 'Handler traps: get, set, has, deleteProperty, etc.', 'Reflect methods mirror the traps and give default behavior.', 'Use for validation, logging, or reactive libraries.'], 'example_code' => "const p = new Proxy({}, {\n  get(t, key) { return t[key] ?? 0; }\n});\np.x; // 0", 'key_points' => ['Proxy intercepts access', 'Handler traps', 'Reflect for defaults'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Object that intercepts property access?', 'code_template' => 'const p = new ___(target, handler);', 'options' => ['Proxy', 'Reflect', 'Interceptor', 'Handler'], 'answer' => 'Proxy']],
];

// PHP extra (beginner add 2; intermediate/advanced replace with 5 each)
$phpBeginnerExtra = [
    ['id' => 'php-l4', 'title' => 'Conditionals & loops', 'content' => 'Control flow in PHP', 'details' => ['if/elseif/else and switch for branching.', 'for, foreach, while, do-while for loops.', 'foreach ($arr as $item) or foreach ($arr as $k => $v).'], 'example_code' => "<?php\nforeach ([1,2,3] as \$n) {\n  echo \$n;\n}\n?>", 'key_points' => ['if/else, switch', 'foreach for arrays', 'for/while'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Loop over array key and value in PHP?', 'code_template' => 'foreach ($arr as $key ___ $val) { }', 'options' => ['=>', '->', '=', ':'], 'answer' => '=>']],
    ['id' => 'php-l5', 'title' => 'Superglobals', 'content' => '$_GET, $_POST, $_SERVER', 'details' => ['$_GET holds query string parameters; $_POST holds form body.', '$_SERVER contains server and request info (e.g. REQUEST_URI).', 'Always validate and sanitize input; never trust client data.'], 'example_code' => "<?php\n\$name = \$_GET['name'] ?? 'Guest';\necho htmlspecialchars(\$name);\n?>", 'key_points' => ['$_GET, $_POST', '$_SERVER', 'Validate input'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'Where are form POST values in PHP?', 'code' => '<form method="POST">', 'options' => ['$_POST', '$_GET', '$_FORM', '$post'], 'answer' => '$_POST']],
];
$phpIntermediate = [
    ['id' => 'php-int-l1', 'title' => 'Classes & objects', 'content' => 'OOP in PHP', 'details' => ['class MyClass { } then $obj = new MyClass();', 'public, protected, private for properties and methods.', '$this refers to the current instance.', 'Constructor: function __construct($arg) { }.'], 'example_code' => "<?php\nclass User {\n  public function __construct(\$n){ \$this->name = \$n; }\n}\n\$u = new User('Alice');\n?>", 'key_points' => ['class, new', 'public/private/protected', '__construct'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'PHP constructor method name?', 'code_template' => 'function ___($x) { $this->x = $x; }', 'options' => ['__construct', 'construct', 'constructor', 'init'], 'answer' => '__construct']],
    ['id' => 'php-int-l2', 'title' => 'PDO & prepared statements', 'content' => 'Safe database access', 'details' => ['PDO: new PDO("mysql:host=...;dbname=...", user, pass).', 'Prepared statements: $stmt = $pdo->prepare("SELECT * FROM users WHERE id = ?");', 'Bind and execute: $stmt->execute([$id]); prevents SQL injection.', 'Fetch: $stmt->fetch(PDO::FETCH_ASSOC) or fetchAll().'], 'example_code' => '<?php' . "\n" . '$stmt = $pdo->prepare(\'SELECT * FROM users WHERE id = ?\');' . "\n" . '$stmt->execute([$id]);' . "\n" . '$row = $stmt->fetch(PDO::FETCH_ASSOC);' . "\n" . '?>', 'key_points' => ['PDO for DB', 'prepare/execute', 'Prevent SQL injection'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'Why use prepared statements?', 'code' => '$pdo->prepare("SELECT * WHERE id = ?");', 'options' => ['Prevent SQL injection', 'Faster only', 'Required by PHP', 'No reason'], 'answer' => 'Prevent SQL injection']],
    ['id' => 'php-int-l3', 'title' => 'Sessions & cookies', 'content' => 'State across requests', 'details' => ['session_start() then $_SESSION["key"] = value;', 'Cookies: setcookie(name, value, expire, path, secure).', 'Session data stored on server; cookie holds session ID.'], 'example_code' => "<?php\nsession_start();\n\$_SESSION['user_id'] = 1;\n?>", 'key_points' => ['session_start', '_SESSION', 'setcookie'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Superglobal that holds session data?', 'code_template' => '$____["key"] = $value;', 'options' => ['SESSION', 'SESSION_DATA', 'COOKIE', 'SERVER'], 'answer' => 'SESSION']],
    ['id' => 'php-int-l4', 'title' => 'File handling', 'content' => 'Read and write files', 'details' => ['file_get_contents(path) reads entire file; file_put_contents(path, data) writes.', 'fopen, fread, fwrite, fclose for streams.', 'is_uploaded_file() and move_uploaded_file() for uploads.'], 'example_code' => '<?php' . "\n" . '$data = file_get_contents(\'config.json\');' . "\n" . '$arr = json_decode($data, true);' . "\n" . '?>', 'key_points' => ['file_get_contents', 'file_put_contents', 'move_uploaded_file'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What does file_get_contents return?', 'code' => "file_get_contents('a.txt')", 'options' => ['String content', 'Resource handle', 'Array', 'Boolean'], 'answer' => 'String content']],
    ['id' => 'php-int-l5', 'title' => 'Namespaces & autoloading', 'content' => 'Organize and load classes', 'details' => ['namespace App\\Models; at top of file; use App\\Models\\User;', 'spl_autoload_register() to load classes by name.', 'PSR-4: namespace maps to directory structure.'], 'example_code' => '<?php' . "\n" . 'namespace App;' . "\n" . 'use App\\Models\\User;' . "\n" . '$u = new User();' . "\n" . '?>', 'key_points' => ['namespace, use', 'spl_autoload_register', 'PSR-4'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Keyword to import a class from another namespace?', 'code_template' => '___ App\\Models\\User;', 'options' => ['use', 'import', 'require', 'namespace'], 'answer' => 'use']],
];
$phpAdvanced = [
    ['id' => 'php-adv-l1', 'title' => 'Exceptions & error handling', 'content' => 'Throw and catch exceptions', 'details' => ['throw new Exception("msg"); try { } catch (Exception $e) { }', 'Custom: class MyException extends Exception { }.', 'finally runs after try/catch. set_exception_handler() for global handler.'], 'example_code' => "<?php\ntry {\n  throw new Exception('Fail');\n} catch (Exception \$e) {\n  echo \$e->getMessage();\n}\n?>", 'key_points' => ['throw, try/catch', 'Custom exceptions', 'finally'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Keyword to throw an exception?', 'code_template' => '___ new Exception("error");', 'options' => ['throw', 'catch', 'raise', 'error'], 'answer' => 'throw']],
    ['id' => 'php-adv-l2', 'title' => 'Traits & interfaces', 'content' => 'Reuse and contracts', 'details' => ['interface I { public function m(); } class C implements I { }.', 'trait T { } use T; inside class to reuse code.', 'A class can implement multiple interfaces; use multiple traits.'], 'example_code' => "<?php\ninterface Loggable { function log(\$m); }\nclass User implements Loggable { function log(\$m){} }\n?>", 'key_points' => ['interface, implements', 'trait, use', 'Multiple interfaces'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What does a class do with an interface?', 'code' => 'class X implements I {}', 'options' => ['Implements its methods', 'Extends it', 'Copies it', 'Ignores it'], 'answer' => 'Implements its methods']],
    ['id' => 'php-adv-l3', 'title' => 'Composer & dependencies', 'content' => 'Manage packages with Composer', 'details' => ['composer require vendor/package adds a dependency.', 'autoload in composer.json for PSR-4 or classmap.', 'composer install installs deps; composer update updates them.'], 'example_code' => "{\n  \"require\": { \"php\": \">=8.0\" },\n  \"autoload\": { \"psr-4\": { \"App\\\\\": \"src/\" } }\n}", 'key_points' => ['composer require', 'autoload', 'install/update'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Command to add a package with Composer?', 'code_template' => 'composer ___ vendor/package', 'options' => ['require', 'add', 'install', 'get'], 'answer' => 'require']],
    ['id' => 'php-adv-l4', 'title' => 'Security best practices', 'content' => 'Secure PHP applications', 'details' => ['Use prepared statements; validate/sanitize all input; escape output.', 'Password hashing: password_hash(), password_verify().', 'HTTPS, secure cookies, CSRF tokens for forms.'], 'example_code' => '<?php' . "\n" . '$hash = password_hash(\'secret\', PASSWORD_DEFAULT);' . "\n" . 'if (password_verify($input, $hash)) { }' . "\n" . '?>', 'key_points' => ['Prepared statements', 'password_hash/verify', 'CSRF, HTTPS'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'Best way to store passwords in PHP?', 'code' => 'password_hash($pass, PASSWORD_DEFAULT)', 'options' => ['Hashed', 'Plain text', 'Encrypted only', 'In cookie'], 'answer' => 'Hashed']],
    ['id' => 'php-adv-l5', 'title' => 'Testing with PHPUnit', 'content' => 'Unit tests in PHP', 'details' => ['PHPUnit: tests in *Test.php; assertSame, assertTrue, etc.', 'TestCase extends PHPUnit\\Framework\\TestCase.', 'Run: ./vendor/bin/phpunit or phpunit.'], 'example_code' => "public function testAdd() {\n  \$this->assertSame(4, add(2, 2));\n}", 'key_points' => ['*Test.php', 'assertSame, assertTrue', 'vendor/bin/phpunit'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Common assertion for exact value equality?', 'code_template' => '$this->___Same(5, $result);', 'options' => ['assert', 'expect', 'check', 'equal'], 'answer' => 'assert']],
];

// SQL extra (beginner add 2; intermediate/advanced replace with 5 each)
$sqlBeginnerExtra = [
    ['id' => 'sql-l4', 'title' => 'Aggregate functions', 'content' => 'COUNT, SUM, AVG, MIN, MAX', 'details' => ['COUNT(*) counts rows; COUNT(column) counts non-NULL.', 'SUM(column), AVG(column), MIN(column), MAX(column).', 'Use with GROUP BY to aggregate per group.'], 'example_code' => "SELECT COUNT(*) FROM users;\nSELECT category, AVG(price) FROM products GROUP BY category;", 'key_points' => ['COUNT, SUM, AVG', 'GROUP BY', 'Aggregates per group'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Function to get the average of a column?', 'code_template' => 'SELECT ___(price) FROM products;', 'options' => ['AVG', 'AVERAGE', 'MEAN', 'SUM'], 'answer' => 'AVG']],
    ['id' => 'sql-l5', 'title' => 'LIKE and wildcards', 'content' => 'Pattern matching in SQL', 'details' => ['LIKE uses % (any chars) and _ (one char): WHERE name LIKE "A%".', 'ILIKE in PostgreSQL for case-insensitive; MySQL use LOWER().', 'NOT LIKE excludes matches.'], 'example_code' => "SELECT * FROM users WHERE name LIKE 'John%';\nSELECT * FROM users WHERE email LIKE '%@gmail.com';", 'key_points' => ['% and _', 'LIKE for patterns', 'Case sensitivity'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => "What does % mean in LIKE 'A%'?", 'code' => "WHERE name LIKE 'A%'", 'options' => ['Any chars after A', 'Exactly one char', 'Literal %', 'Nothing'], 'answer' => 'Any chars after A']],
];
$sqlIntermediate = [
    ['id' => 'sql-int-l1', 'title' => 'Subqueries', 'content' => 'Queries inside queries', 'details' => ['Subquery in WHERE: WHERE id IN (SELECT user_id FROM orders).', 'Subquery in FROM: SELECT * FROM (SELECT ...) AS sub.', 'Correlated subquery references outer query.'], 'example_code' => "SELECT * FROM users\nWHERE id IN (SELECT user_id FROM orders WHERE total > 100);", 'key_points' => ['IN (subquery)', 'FROM (subquery)', 'Correlated subqueries'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Keyword to match against result of inner query?', 'code_template' => 'WHERE id ___ (SELECT id FROM t);', 'options' => ['IN', '=','MATCH', 'EQ'], 'answer' => 'IN']],
    ['id' => 'sql-int-l2', 'title' => 'Indexes & performance', 'content' => 'Speed up queries with indexes', 'details' => ['CREATE INDEX idx_name ON table(column); speeds up WHERE and JOIN on that column.', 'Primary key and UNIQUE create indexes automatically.', 'Too many indexes slow down INSERT/UPDATE.'], 'example_code' => "CREATE INDEX idx_user_email ON users(email);\nCREATE UNIQUE INDEX idx_username ON users(username);", 'key_points' => ['CREATE INDEX', 'Speed WHERE/JOIN', 'Trade-off with writes'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What do indexes improve?', 'code' => 'CREATE INDEX idx ON users(email);', 'options' => ['Query speed', 'Storage', 'Security', 'Backup'], 'answer' => 'Query speed']],
    ['id' => 'sql-int-l3', 'title' => 'Transactions', 'content' => 'ACID with BEGIN/COMMIT/ROLLBACK', 'details' => ['BEGIN or START TRANSACTION; then COMMIT; or ROLLBACK;', 'All or nothing: if one statement fails, roll back.', 'Use for multi-step updates that must stay consistent.'], 'example_code' => "BEGIN;\nUPDATE accounts SET balance = balance - 100 WHERE id = 1;\nUPDATE accounts SET balance = balance + 100 WHERE id = 2;\nCOMMIT;", 'key_points' => ['BEGIN, COMMIT, ROLLBACK', 'ACID', 'Consistency'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Command to cancel a transaction?', 'code_template' => 'BEGIN; ... ___;', 'options' => ['ROLLBACK', 'CANCEL', 'UNDO', 'ABORT'], 'answer' => 'ROLLBACK']],
    ['id' => 'sql-int-l4', 'title' => 'GROUP BY & HAVING', 'content' => 'Filter grouped results', 'details' => ['GROUP BY column groups rows; aggregates apply per group.', 'HAVING filters after grouping: HAVING COUNT(*) > 5.', 'WHERE filters before grouping; HAVING after.'], 'example_code' => "SELECT category, COUNT(*) as n\nFROM products\nGROUP BY category\nHAVING COUNT(*) > 10;", 'key_points' => ['GROUP BY', 'HAVING after GROUP', 'WHERE before GROUP'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'Filter groups by aggregate condition?', 'code' => 'GROUP BY x HAVING COUNT(*) > 1', 'options' => ['HAVING', 'WHERE', 'FILTER', 'GROUP WHERE'], 'answer' => 'HAVING']],
    ['id' => 'sql-int-l5', 'title' => 'UNION & set operations', 'content' => 'Combine result sets', 'details' => ['UNION combines two SELECTs; duplicates removed. UNION ALL keeps duplicates.', 'Same number of columns; compatible types.', 'INTERSECT and EXCEPT in some DBs.'], 'example_code' => "SELECT name FROM users\nUNION\nSELECT name FROM admins;", 'key_points' => ['UNION, UNION ALL', 'Same columns', 'INTERSECT/EXCEPT'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Keyword to combine two SELECT results?', 'code_template' => 'SELECT a ___ SELECT b;', 'options' => ['UNION', 'JOIN', 'MERGE', 'ADD'], 'answer' => 'UNION']],
];
$sqlAdvanced = [
    ['id' => 'sql-adv-l1', 'title' => 'Window functions', 'content' => 'ROW_NUMBER, RANK, OVER', 'details' => ['OVER (PARTITION BY col ORDER BY col) defines the window.', 'ROW_NUMBER(), RANK(), DENSE_RANK() assign row numbers per partition.', 'LAG(col), LEAD(col) access previous/next row.'], 'example_code' => "SELECT name, score,\n  ROW_NUMBER() OVER (ORDER BY score DESC) as rn\nFROM results;", 'key_points' => ['OVER (PARTITION BY, ORDER BY)', 'ROW_NUMBER, RANK', 'LAG, LEAD'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Clause that defines a window for a function?', 'code_template' => 'ROW_NUMBER() ___ (ORDER BY x)', 'options' => ['OVER', 'PARTITION', 'WINDOW', 'BY'], 'answer' => 'OVER']],
    ['id' => 'sql-adv-l2', 'title' => 'CTEs (Common Table Expressions)', 'content' => 'WITH clause for readable queries', 'details' => ['WITH cte AS (SELECT ...) SELECT * FROM cte;', 'CTEs make complex queries readable; can be recursive.', 'Recursive: WITH RECURSIVE cte AS (anchor UNION SELECT ... FROM cte).'], 'example_code' => "WITH top_users AS (\n  SELECT * FROM users ORDER BY score DESC LIMIT 10\n)\nSELECT * FROM top_users WHERE active = 1;", 'key_points' => ['WITH ... AS', 'Readable subqueries', 'Recursive CTEs'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What does WITH cte AS (...) do?', 'code' => 'WITH cte AS (SELECT 1) SELECT * FROM cte', 'options' => ['Names a subquery', 'Creates table', 'Loop', 'Nothing'], 'answer' => 'Names a subquery']],
    ['id' => 'sql-adv-l3', 'title' => 'Normalization', 'content' => 'Reduce redundancy', 'details' => ['1NF: atomic values; 2NF: no partial dependency on key; 3NF: no transitive dependency.', 'Split tables; use foreign keys.', 'Denormalization sometimes for read performance.'], 'example_code' => "-- Separate users and orders\nusers(id, name)\norders(id, user_id, total)", 'key_points' => ['1NF, 2NF, 3NF', 'Foreign keys', 'Denormalize for reads'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Form that requires atomic column values?', 'code_template' => '___ NF', 'options' => ['1st', '2nd', '3rd', '4th'], 'answer' => '1st']],
    ['id' => 'sql-adv-l4', 'title' => 'Stored procedures & triggers', 'content' => 'Logic inside the database', 'details' => ['Stored procedure: CREATE PROCEDURE name() BEGIN ... END;', 'Trigger: runs before/after INSERT/UPDATE/DELETE.', 'Use for enforced business rules or audit logs.'], 'example_code' => "CREATE TRIGGER after_insert\nAFTER INSERT ON orders\nFOR EACH ROW\nBEGIN\n  UPDATE stats SET total_orders = total_orders + 1;\nEND;", 'key_points' => ['CREATE PROCEDURE', 'Triggers BEFORE/AFTER', 'Business rules'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'When does a trigger run?', 'code' => 'AFTER INSERT ON orders', 'options' => ['After row inserted', 'Before query', 'Never', 'On login'], 'answer' => 'After row inserted']],
    ['id' => 'sql-adv-l5', 'title' => 'Query optimization', 'content' => 'EXPLAIN and tuning', 'details' => ['EXPLAIN (or EXPLAIN ANALYZE) shows how the DB executes a query.', 'Look for full table scans; add indexes or rewrite.', 'Avoid SELECT *; limit result sets; use pagination.'], 'example_code' => "EXPLAIN SELECT * FROM users WHERE email = 'a@b.com';", 'key_points' => ['EXPLAIN', 'Index usage', 'Avoid full scan'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Command to see how a query is executed?', 'code_template' => '___ SELECT ...', 'options' => ['EXPLAIN', 'SHOW', 'DESCRIBE', 'DEBUG'], 'answer' => 'EXPLAIN']],
];

// CSS extra (beginner add 2; intermediate/advanced replace with 5 each)
$cssBeginnerExtra = [
    ['id' => 'css-l4', 'title' => 'Colors & units', 'content' => 'Hex, RGB, and relative units', 'details' => ['Hex: #ff0000 or #f00; RGB: rgb(255,0,0); RGBA for transparency.', 'rem is relative to root font-size; em to parent.', 'vw/vh are viewport width/height (e.g. 50vw).'], 'example_code' => "color: #3498db;\nfont-size: 1.5rem;\nwidth: 50vw;", 'key_points' => ['Hex, rgb, rgba', 'rem, em', 'vw, vh'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Unit relative to root font size?', 'code_template' => 'font-size: 1.5___;', 'options' => ['rem', 'em', 'px', 'vw'], 'answer' => 'rem']],
    ['id' => 'css-l5', 'title' => 'Box model', 'content' => 'Margin, border, padding', 'details' => ['Content + padding + border + margin = box model.', 'box-sizing: border-box includes padding and border in width/height.', 'Margin collapses between adjacent elements.'], 'example_code' => ".box {\n  width: 200px;\n  padding: 20px;\n  border: 2px solid #333;\n  box-sizing: border-box;\n}", 'key_points' => ['padding, border, margin', 'box-sizing: border-box', 'Margin collapse'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What does border-box change?', 'code' => 'box-sizing: border-box', 'options' => ['Width includes padding/border', 'Removes border', 'Adds margin', 'Nothing'], 'answer' => 'Width includes padding/border']],
];
$cssIntermediate = [
    ['id' => 'css-int-l1', 'title' => 'Grid layout', 'content' => 'Two-dimensional layout with CSS Grid', 'details' => ['display: grid; then grid-template-columns and grid-template-rows.', 'gap for spacing; grid-column/grid-row to span.', 'fr unit: fraction of available space.'], 'example_code' => ".grid {\n  display: grid;\n  grid-template-columns: 1fr 1fr 1fr;\n  gap: 16px;\n}", 'key_points' => ['grid-template-columns/rows', 'fr, gap', 'grid-column/row'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Property to set number of columns in Grid?', 'code_template' => 'grid-___-columns: 1fr 1fr;', 'options' => ['template', 'set', 'columns', 'define'], 'answer' => 'template']],
    ['id' => 'css-int-l2', 'title' => 'Transitions & transforms', 'content' => 'Animate with transition and transform', 'details' => ['transition: property duration easing; e.g. transition: all 0.3s ease;', 'transform: translate(), rotate(), scale();', 'Trigger on hover or class change.'], 'example_code' => ".btn {\n  transition: transform 0.2s ease;\n}\n.btn:hover { transform: scale(1.05); }", 'key_points' => ['transition', 'transform', 'hover trigger'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What does transform: scale(2) do?', 'code' => 'transform: scale(2);', 'options' => ['Doubles size', 'Moves right', 'Rotates', 'Fades'], 'answer' => 'Doubles size']],
    ['id' => 'css-int-l3', 'title' => 'Custom properties (variables)', 'content' => 'Reuse values with --var', 'details' => ['Define: --primary: #3498db; use: color: var(--primary);', 'Inherit; can set on :root for global.', 'Override in media queries or scoped blocks.'], 'example_code' => ":root { --primary: #3498db; --spacing: 16px; }\n.button { background: var(--primary); padding: var(--spacing); }", 'key_points' => ['--name: value', 'var(--name)', ':root'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'How do you use a CSS variable value?', 'code_template' => 'color: ___(--primary);', 'options' => ['var', 'use', 'get', 'variable'], 'answer' => 'var']],
    ['id' => 'css-int-l4', 'title' => 'Pseudo-classes & pseudo-elements', 'content' => 'More selectors', 'details' => [':hover, :focus, :active for states; :nth-child(n) for position.', '::before and ::after create virtual elements; need content.', ':first-child, :last-child, :not(selector).'], 'example_code' => "a:hover { color: blue; }\nli:nth-child(odd) { background: #f5f5f5; }\n.block::before { content: '»'; }", 'key_points' => [':hover, :focus', ':nth-child', '::before, ::after'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What does :nth-child(2n) select?', 'code' => 'li:nth-child(2n)', 'options' => ['Even items', 'Odd items', 'Second only', 'All'], 'answer' => 'Even items']],
    ['id' => 'css-int-l5', 'title' => 'BEM naming', 'content' => 'Block Element Modifier', 'details' => ['Block: .card; Element: .card__title; Modifier: .card--featured.', 'Avoid deep nesting; flat class names.', 'Makes CSS predictable and reusable.'], 'example_code' => ".card { }\n.card__title { }\n.card__body { }\n.card--featured { }", 'key_points' => ['Block__Element', 'Block--Modifier', 'Flat structure'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'BEM modifier uses how many dashes?', 'code_template' => '.card___featured', 'options' => ['--', '-', '__', '---'], 'answer' => '--']],
];
$cssAdvanced = [
    ['id' => 'css-adv-l1', 'title' => 'Keyframe animations', 'content' => '@keyframes and animation', 'details' => ['@keyframes name { 0% {} 100% {} } then animation: name duration;', 'animation-iteration-count, animation-direction, animation-fill-mode.', 'Prefer for multi-step; transition for simple toggle.'], 'example_code' => "@keyframes fadeIn {\n  from { opacity: 0; }\n  to { opacity: 1; }\n}\n.box { animation: fadeIn 1s ease; }", 'key_points' => ['@keyframes', 'animation property', 'from/to or %'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'At-rule for defining animation steps?', 'code_template' => '@___ fadeIn { }', 'options' => ['keyframes', 'animation', 'frames', 'keyframe'], 'answer' => 'keyframes']],
    ['id' => 'css-adv-l2', 'title' => 'Layout: clamp & min/max', 'content' => 'Fluid typography and spacing', 'details' => ['clamp(min, preferred, max): font-size: clamp(1rem, 2vw, 2rem);', 'min(), max() for responsive values.', 'Fluid spacing without many media queries.'], 'example_code' => "font-size: clamp(1rem, 2vw + 1rem, 2rem);\nwidth: min(100%, 1200px);", 'key_points' => ['clamp', 'min, max', 'Fluid values'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What does clamp(1rem, 5vw, 2rem) do?', 'code' => 'clamp(1rem, 5vw, 2rem)', 'options' => ['Bounds size between 1rem and 2rem', 'Sets fixed 2rem', 'Only 5vw', 'Error'], 'answer' => 'Bounds size between 1rem and 2rem']],
    ['id' => 'css-adv-l3', 'title' => 'Accessibility: focus & contrast', 'content' => 'Visible focus and contrast', 'details' => [':focus-visible for keyboard focus; outline or box-shadow for visibility.', 'prefers-reduced-motion: reduce to tone down animations.', 'Contrast ratios: 4.5:1 normal text, 3:1 large.'], 'example_code' => "button:focus-visible { outline: 2px solid blue; }\n@media (prefers-reduced-motion: reduce) {\n  * { animation: none; }\n}", 'key_points' => [':focus-visible', 'prefers-reduced-motion', 'Contrast'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Pseudo-class for keyboard focus only?', 'code_template' => 'button:___ { outline: 2px solid blue; }', 'options' => ['focus-visible', 'focus', 'keyboard', 'tab'], 'answer' => 'focus-visible']],
    ['id' => 'css-adv-l4', 'title' => 'Container queries', 'content' => 'Style by container size', 'details' => ['@container (min-width: 400px) { } styles by parent size, not viewport.', 'container-type: inline-size on parent; then query inside.', 'Use for reusable components that adapt to their wrapper.'], 'example_code' => ".card { container-type: inline-size; }\n@container (min-width: 400px) {\n  .card { display: grid; }\n}", 'key_points' => ['@container', 'container-type', 'Component-based responsive'], 'xp' => 50, 'game' => ['type' => 'predict_output', 'question' => 'What do container queries depend on?', 'code' => '@container (min-width: 400px)', 'options' => ['Parent size', 'Viewport', 'Font size', 'Color'], 'answer' => 'Parent size']],
    ['id' => 'css-adv-l5', 'title' => 'Performance: contain & content-visibility', 'content' => 'Optimize rendering', 'details' => ['contain: layout paint; tells browser to limit layout/paint to element.', 'content-visibility: auto skips rendering off-screen content.', 'Reduces reflows and speeds up long pages.'], 'example_code' => ".section { contain: layout paint; }\n.article { content-visibility: auto; }", 'key_points' => ['contain', 'content-visibility', 'Rendering optimization'], 'xp' => 50, 'game' => ['type' => 'fill_blank', 'question' => 'Property to skip rendering off-screen content?', 'code_template' => '___-visibility: auto;', 'options' => ['content', 'visibility', 'render', 'display'], 'answer' => 'content']],
];

foreach ($modules as &$module) {
    $id = $module['id'];
    $difficulty = $module['difficulty'] ?? 'beginner';
    $existingLessons = $module['lessons'] ?? [];

    if (strpos($id, 'html-basics') === 0) {
        if ($id === 'html-basics') {
            $module['lessons'] = array_merge($existingLessons, $extraLessons['html-basics']);
        } elseif ($id === 'html-basics-intermediate') {
            $module['lessons'] = $extraLessons['html-basics-intermediate'];
        } elseif ($id === 'html-basics-advanced') {
            $module['lessons'] = $extraLessons['html-basics-advanced'];
        }
    } elseif (strpos($id, 'javascript-fundamentals') === 0) {
        if ($id === 'javascript-fundamentals') {
            $module['lessons'] = array_merge($existingLessons, $jsBeginnerExtra);
        } elseif ($id === 'javascript-fundamentals-intermediate') {
            $module['lessons'] = $jsIntermediate;
        } elseif ($id === 'javascript-fundamentals-advanced') {
            $module['lessons'] = $jsAdvanced;
        }
    } elseif (strpos($id, 'php-development') === 0) {
        if ($id === 'php-development') {
            $module['lessons'] = array_merge($existingLessons, $phpBeginnerExtra);
        } elseif ($id === 'php-development-intermediate') {
            $module['lessons'] = $phpIntermediate;
        } elseif ($id === 'php-development-advanced') {
            $module['lessons'] = $phpAdvanced;
        }
    } elseif (strpos($id, 'sql-databases') === 0) {
        if ($id === 'sql-databases') {
            $module['lessons'] = array_merge($existingLessons, $sqlBeginnerExtra);
        } elseif ($id === 'sql-databases-intermediate') {
            $module['lessons'] = $sqlIntermediate;
        } elseif ($id === 'sql-databases-advanced') {
            $module['lessons'] = $sqlAdvanced;
        }
    } elseif (strpos($id, 'css-styling') === 0) {
        if ($id === 'css-styling') {
            $module['lessons'] = array_merge($existingLessons, $cssBeginnerExtra);
        } elseif ($id === 'css-styling-intermediate') {
            $module['lessons'] = $cssIntermediate;
        } elseif ($id === 'css-styling-advanced') {
            $module['lessons'] = $cssAdvanced;
        }
    }

    $totalXp = 0;
    foreach ($module['lessons'] as $lesson) {
        $totalXp += (int) ($lesson['xp'] ?? 50);
    }
    $module['total_xp'] = $totalXp;
}

$out = json_encode($modules, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
if ($out === false) {
    die("JSON encode failed\n");
}
file_put_contents($path, $out);
echo "Updated data/modules.json: more lessons per module, unique content per difficulty.\n";
